CC = "commentOnlyLine"


def r(**k):
    k.setdefault("lang", "js")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "javascript", "security"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


# JavaScript/TypeScript security pack: precise injection / XSS-sink / prototype-pollution / CORS / JWT
# patterns. Concept origins cited (CWE, OWASP, ESLint / eslint-plugin-security, SonarJS); prose is
# authored clean-room. Known-noisy heuristics (Math.random, non-literal new RegExp) are deliberately
# omitted to keep the pack low-false-positive.
RULES = [
    r(id="js-eval-call", type="hotspot", qual="sec", sev="high", cwe="CWE-95", owasp="A03:2021",
      title="Use of eval()", desc="eval() executes arbitrary strings as code and is a code-injection vector.",
      rationale="eval on any attacker-influenced string runs arbitrary code in the page/process.",
      remediation="Replace eval with an explicit parser (e.g. JSON.parse) or a lookup table.",
      source="https://cwe.mitre.org/data/definitions/95.html",
      re=r"\beval\s*\(", nc="const result = eval(userInput);", c="const result = JSON.parse(userInput);"),
    r(id="js-new-function", type="hotspot", qual="sec", sev="high", cwe="CWE-95", owasp="A03:2021",
      title="Function constructor", desc="new Function(...) compiles a string into code, like eval.",
      rationale="The Function constructor evaluates its string body as code, enabling injection.",
      remediation="Avoid building functions from strings; use a normal function or a whitelist.",
      source="https://cwe.mitre.org/data/definitions/95.html",
      re=r"new\s+Function\s*\(", nc='const f = new Function("return " + expr);', c="const f = () => compute(expr);"),
    r(id="js-execscript", type="vuln", qual="sec", sev="high", cwe="CWE-95", owasp="A03:2021",
      title="execScript() code execution", desc="execScript executes a string as script code.",
      rationale="The legacy execScript API runs its string argument as code, enabling injection.",
      remediation="Remove execScript; call the function directly.",
      source="https://cwe.mitre.org/data/definitions/95.html",
      re=r"\bexecScript\s*\(", nc='execScript(code, "JScript");', c="runHandler(code);"),
    r(id="js-setinterval-string", type="hotspot", qual="sec", sev="medium", cwe="CWE-95", owasp="A03:2021",
      title="setInterval with a string argument", desc="setInterval(\"code\", ...) evaluates the string like eval.",
      rationale="Passing a string to setInterval implicitly calls eval on each tick.",
      remediation="Pass a function reference: setInterval(fn, delay).",
      source="https://cwe.mitre.org/data/definitions/95.html",
      re=r"setInterval\s*\(\s*[\"'`]", nc='setInterval("poll()", 1000);', c="setInterval(poll, 1000);"),
    r(id="js-document-write", type="hotspot", qual="sec", sev="medium", cwe="CWE-79", owasp="A03:2021",
      title="document.write()", desc="document.write injects markup directly and is a common DOM-XSS sink.",
      rationale="Writing unescaped input via document.write allows script injection into the page.",
      remediation="Build DOM nodes with textContent / createElement, or a templating library that escapes.",
      source="https://cwe.mitre.org/data/definitions/79.html",
      re=r"document\.write(ln)?\s*\(", nc="document.write(userInput);", c="container.textContent = userInput;"),
    r(id="js-inner-html-assign", type="hotspot", qual="sec", sev="medium", cwe="CWE-79", owasp="A03:2021",
      title="Assignment to innerHTML", desc="Assigning to innerHTML renders markup and is a DOM-XSS sink.",
      rationale="Setting innerHTML from untrusted data injects and executes attacker markup.",
      remediation="Use textContent for text, or sanitize the HTML with a vetted library.",
      source="https://cwe.mitre.org/data/definitions/79.html",
      re=r"\.innerHTML\s*=\s*[^=]", nc="el.innerHTML = userBio;", c="if (el.innerHTML === cached) return;"),
    r(id="js-dangerously-set-inner-html", type="hotspot", qual="sec", sev="medium", cwe="CWE-79", owasp="A03:2021",
      title="React dangerouslySetInnerHTML", desc="dangerouslySetInnerHTML bypasses React's escaping.",
      rationale="This prop injects raw HTML, so untrusted values become a stored/reflected XSS.",
      remediation="Render text as children, or sanitize the HTML before passing it.",
      source="https://cwe.mitre.org/data/definitions/79.html",
      re=r"dangerouslySetInnerHTML", nc="<div dangerouslySetInnerHTML={{__html: userBio}} />", c="<div>{userBio}</div>"),
    r(id="js-angular-bypass-security", type="hotspot", qual="sec", sev="medium", cwe="CWE-79", owasp="A03:2021",
      title="Angular bypassSecurityTrust", desc="bypassSecurityTrust* disables Angular's built-in sanitizer.",
      rationale="Marking untrusted values as trusted defeats Angular's contextual escaping.",
      remediation="Let Angular sanitize the value, or validate it against a strict allowlist first.",
      source="https://cwe.mitre.org/data/definitions/79.html",
      re=r"bypassSecurityTrust", nc="const html = this.sanitizer.bypassSecurityTrustHtml(userHtml);", c="const html = this.sanitizer.sanitize(ctx, userHtml);"),
    r(id="js-vue-v-html", type="hotspot", qual="sec", sev="medium", cwe="CWE-79", owasp="A03:2021",
      title="Vue v-html directive", desc="v-html renders raw HTML and bypasses Vue's escaping.",
      rationale="Binding untrusted content to v-html injects attacker markup, causing XSS.",
      remediation="Use text interpolation ({{ }}) or sanitize before binding to v-html.",
      source="https://cwe.mitre.org/data/definitions/79.html",
      re=r"\bv-html\s*=", nc='<div v-html="userContent"></div>', c="<div>{{ userContent }}</div>"),
    r(id="js-proto-pollution-bracket", type="hotspot", qual="sec", sev="medium", cwe="CWE-1321", owasp="A03:2021",
      title="__proto__ bracket access", desc="Indexing an object with the \"__proto__\" key can pollute the prototype chain.",
      rationale="Writing to obj[\"__proto__\"] mutates Object.prototype, affecting every object.",
      remediation="Use a Map, a null-prototype object, or reject __proto__/constructor/prototype keys.",
      source="https://cwe.mitre.org/data/definitions/1321.html",
      re=r"\[\s*[\"']__proto__[\"']\s*\]", nc='target["__proto__"]["polluted"] = true;', c='target["name"] = value;'),
    r(id="js-proto-assign", type="hotspot", qual="sec", sev="medium", cwe="CWE-1321", owasp="A03:2021",
      title="Assignment to __proto__", desc="Assigning to .__proto__ mutates an object's prototype at runtime.",
      rationale="Setting __proto__ from untrusted data can pollute prototypes or subvert type checks.",
      remediation="Use Object.create / Object.setPrototypeOf deliberately, never from external input.",
      source="https://cwe.mitre.org/data/definitions/1321.html",
      re=r"\.__proto__\s*=\s*[^=]", nc="obj.__proto__ = attackerControlled;", c="if (obj.__proto__ === Base.prototype) ok();"),
    r(id="js-cors-wildcard", type="hotspot", qual="sec", sev="medium", cwe="CWE-942", owasp="A05:2021",
      title="Wildcard CORS origin", desc="Access-Control-Allow-Origin: * lets any site read authenticated responses.",
      rationale="A wildcard CORS origin defeats the same-origin policy for the response.",
      remediation="Echo a validated allowlisted origin instead of \"*\".",
      source="https://cwe.mitre.org/data/definitions/942.html",
      re=r"Access-Control-Allow-Origin[\"'`]\s*[,:]\s*[\"'`]\*[\"'`]", nc='res.setHeader("Access-Control-Allow-Origin", "*");', c='res.setHeader("Access-Control-Allow-Origin", allowedOrigin);'),
    r(id="js-jwt-decode-no-verify", type="hotspot", qual="sec", sev="medium", cwe="CWE-347", owasp="A02:2021",
      title="JWT decoded without verification", desc="jwt.decode() reads a token without checking its signature.",
      rationale="Trusting decoded JWT claims without verifying the signature accepts forged tokens.",
      remediation="Use jwt.verify() with the expected algorithm and key.",
      source="https://cwe.mitre.org/data/definitions/347.html",
      re=r"jwt\.decode\s*\(", nc="const claims = jwt.decode(token);", c="const claims = jwt.verify(token, secret);"),
    r(id="js-foreach-async", type="bug", qual="rel", sev="medium", cwe="", title="async callback passed to forEach",
      desc="Array.forEach ignores the promise returned by an async callback, so it does not await.",
      rationale="forEach does not await async callbacks; errors are unhandled and ordering is lost.",
      remediation="Use a for..of loop with await, or Promise.all(map(...)).",
      source="https://eslint.org/docs/latest/rules/no-restricted-syntax",
      re=r"\.forEach\s*\(\s*async\b", nc="items.forEach(async (x) => { await save(x); });", c="for (const x of items) { await save(x); }"),
    r(id="js-unneeded-ternary", type="smell", qual="maint", sev="low", cwe="", title="Ternary returning boolean literals",
      desc="cond ? true : false is just the condition (coerced to boolean).",
      rationale="A ternary that yields true/false is redundant and harder to read than the condition.",
      remediation="Use the condition directly, or Boolean(cond) / !!cond when coercion is needed.",
      source="https://eslint.org/docs/latest/rules/no-unneeded-ternary",
      re=r"\?\s*true\s*:\s*false\b", nc="const enabled = ready ? true : false;", c="const enabled = Boolean(ready);"),
]
