// HTML report renderer. It turns the format-agnostic ports.ReportDocument into a
// standalone, self-contained HTML document via html/template (auto-escaping closes
// the injection surface – finding titles/descriptions are untrusted operator text).
// Output is deterministic: html/template emits identical bytes for identical input,
// so the SHA-256 seal is reproducible (chain-of-custody).
package report

import (
	"bytes"
	"context"
	"encoding/base64"
	"fmt"
	"html/template"

	"github.com/KKloudTarus/synapse-ce/internal/usecase/ports"
)

// HTMLRenderer implements ports.DocRenderer for HTML output.
type HTMLRenderer struct {
	tmpl *template.Template
}

var _ ports.DocRenderer = (*HTMLRenderer)(nil)

// imageDataURI builds a base64 data: URI for an exhibit and marks it trusted for the
// img src context. This is safe ONLY because the report builder restricts exhibit
// MIME to raster types (image/png|jpeg|gif) – never SVG/HTML – so the data URI cannot
// carry script. The caption is rendered through normal auto-escaping.
func imageDataURI(img ports.ReportImage) template.URL {
	return template.URL("data:" + img.MIME + ";base64," + base64.StdEncoding.EncodeToString(img.Data))
}

// NewHTMLRenderer compiles the report template once. It panics only on a
// programmer error (a malformed constant template), never on input.
func NewHTMLRenderer() *HTMLRenderer {
	tmpl := template.New("report").Funcs(template.FuncMap{"imageDataURI": imageDataURI})
	return &HTMLRenderer{tmpl: template.Must(tmpl.Parse(htmlTemplate))}
}

// Render writes the document as a self-contained HTML page.
func (h *HTMLRenderer) Render(_ context.Context, doc ports.ReportDocument) ([]byte, error) {
	var buf bytes.Buffer
	if err := h.tmpl.Execute(&buf, doc); err != nil {
		return nil, fmt.Errorf("execute html template: %w", err)
	}
	return buf.Bytes(), nil
}

// htmlTemplate is a single self-contained page (inline CSS, no external assets) so
// the report is portable and renders identically offline.
const htmlTemplate = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{.Title}}</title>
<style>
:root{color-scheme:light}
*{box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif;color:#1a1a1a;background:#fff;margin:0;padding:2.5rem;line-height:1.5}
.wrap{max-width:60rem;margin:0 auto}
h1{font-size:1.6rem;margin:0 0 .25rem}
.subtitle{color:#666;font-size:.9rem;margin:0 0 2rem;font-variant-numeric:tabular-nums}
h2{font-size:1.15rem;margin:2rem 0 .75rem;padding-bottom:.3rem;border-bottom:2px solid #e5e7eb}
p{margin:.5rem 0;white-space:pre-wrap;word-wrap:break-word}
table{border-collapse:collapse;width:100%;margin:.75rem 0;font-size:.875rem}
th,td{border:1px solid #e5e7eb;padding:.45rem .6rem;text-align:left;vertical-align:top}
th{background:#f8fafc;font-weight:600}
td{font-variant-numeric:tabular-nums}
figure{margin:1.25rem 0}
figure img{display:block;max-width:100%;height:auto;border:1px solid #e5e7eb;border-radius:4px}
figcaption{color:#666;font-size:.8rem;margin-top:.35rem;font-variant-numeric:tabular-nums}
footer{margin-top:3rem;padding-top:1rem;border-top:1px solid #e5e7eb;color:#888;font-size:.8rem}
</style>
</head>
<body>
<div class="wrap">
<h1>{{.Title}}</h1>
<p class="subtitle">{{.Subtitle}}</p>
{{range .Sections}}
<section>
<h2>{{.Heading}}</h2>
{{range .Paragraphs}}<p>{{.}}</p>
{{end}}
{{with .Table}}<table>
<thead><tr>{{range .Headers}}<th>{{.}}</th>{{end}}</tr></thead>
<tbody>
{{range .Rows}}<tr>{{range .}}<td>{{.}}</td>{{end}}</tr>
{{end}}</tbody>
</table>
{{end}}
{{range .Images}}<figure><img src="{{imageDataURI .}}" alt="{{.Caption}}"><figcaption>{{.Caption}}</figcaption></figure>
{{end}}
</section>
{{end}}
<footer>Generated by Synapse {{.Version}} – templated from stored data, no AI in the report path.</footer>
</div>
</body>
</html>
`
