package ownsbom

import (
	"context"
	"path/filepath"
	"testing"

	"github.com/KKloudTarus/synapse-ce/internal/domain/sbom"
)

const cargoLockFixture = `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "myapp"
version = "0.1.0"
dependencies = [
 "serde",
 "criterion",
]

[[package]]
name = "serde"
version = "1.0.197"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "3fb1c873e1b9b056a4dc4c0c198b24c3ffa059243875552b2bd0933b1aee4ce2"
dependencies = [
 "serde_derive",
]

[[package]]
name = "serde_derive"
version = "1.0.197"

[[package]]
name = "criterion"
version = "0.5.1"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "mockall"
version = "0.12.1"

[[package]]
name = "tokio-test"
version = "0.4.3"

[[package]]
name = "version"
version = "3.0.0"
`

const cargoTomlFixture = `[package]
name = "myapp"
version = "0.1.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
criterion = "0.5"
mockall = { version = "0.12", features = ["nightly"] }

[dev-dependencies.tokio-test]
version = "0.4"
features = ["macros"]
`

func TestCargoParseWithCompanion(t *testing.T) {
	dir := t.TempDir()
	mustWrite(t, filepath.Join(dir, "Cargo.lock"), cargoLockFixture)
	mustWrite(t, filepath.Join(dir, "Cargo.toml"), cargoTomlFixture)

	comps, deps, err := Cargo{}.Parse(context.Background(), ParseInput{
		Dir: dir, Path: filepath.Join(dir, "Cargo.lock"), Content: []byte(cargoLockFixture),
	})
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if len(comps) != 7 {
		t.Fatalf("want 7 crates, got %d: %+v", len(comps), comps)
	}
	// edges: the dependency graph is resolved from Cargo.lock's `dependencies` arrays (by unique
	// name -> version), in file order.
	edges := map[string][]string{}
	for _, d := range deps {
		edges[d.Ref] = d.DependsOn
	}
	if on := edges["pkg:cargo/myapp@0.1.0"]; len(on) != 2 ||
		on[0] != "pkg:cargo/serde@1.0.197" || on[1] != "pkg:cargo/criterion@0.5.1" {
		t.Errorf("myapp edges = %v, want [serde criterion]", on)
	}
	if on := edges["pkg:cargo/serde@1.0.197"]; len(on) != 1 || on[0] != "pkg:cargo/serde_derive@1.0.197" {
		t.Errorf("serde edges = %v, want [serde_derive]", on)
	}
	if _, ok := edges["pkg:cargo/version@3.0.0"]; ok {
		t.Errorf("leaf crate 'version' must have no dependency edges")
	}
	byName := map[string]sbom.Component{}
	for _, c := range comps {
		byName[c.Name] = c
	}
	// resolved version + cargo PURL
	if c := byName["serde"]; c.Version != "1.0.197" || c.PURL != "pkg:cargo/serde@1.0.197" {
		t.Errorf("serde = %+v, want 1.0.197 / pkg:cargo/serde@1.0.197", c)
	}
	// the [[package]] checksum is captured as a SHA256 component Checksum
	if ck := byName["serde"].Checksums; len(ck) != 1 || ck[0].Algorithm != "SHA256" || ck[0].Value != "3fb1c873e1b9b056a4dc4c0c198b24c3ffa059243875552b2bd0933b1aee4ce2" {
		t.Errorf("serde checksum = %+v, want [{SHA256 3fb1c8…}]", ck)
	}
	// a crate without a checksum line stays without one
	if ck := byName["serde_derive"].Checksums; len(ck) != 0 {
		t.Errorf("serde_derive has no checksum line, want none, got %+v", ck)
	}
	// THE POINT: the companion Cargo.toml scopes dev-deps as development (first parser to exercise
	// ParseInput.Dir) – across all three declaration forms.
	for _, devCrate := range []string{
		"criterion",  // plain: key = "ver"
		"mockall",    // inline: key = { version = … }
		"tokio-test", // sub-table: [dev-dependencies.tokio-test]
	} {
		if c := byName[devCrate]; c.Scope != sbom.ScopeDevelopment {
			t.Errorf("%s must be dev-scoped from the companion Cargo.toml: scope=%q", devCrate, c.Scope)
		}
	}
	// a non-dev crate stays production
	if c := byName["serde"]; c.Scope != sbom.ScopeProduction {
		t.Errorf("serde scope = %q, want production", c.Scope)
	}
	// REGRESSION: a real production crate named "version" must NOT be mis-scoped dev just because the
	// [dev-dependencies.tokio-test] sub-table BODY contains a `version = …` line (its keys aren't crates).
	if c := byName["version"]; c.Scope != sbom.ScopeProduction {
		t.Errorf("production crate 'version' must NOT be dev-scoped (sub-table body keys are not crate names): scope=%q", c.Scope)
	}
}

func TestCargoParseNoCompanion(t *testing.T) {
	// no Dir / no Cargo.toml -> best-effort: every crate production-scoped, no crash, no dev refinement
	comps, _, err := Cargo{}.Parse(context.Background(), ParseInput{Path: "Cargo.lock", Content: []byte(cargoLockFixture)})
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if len(comps) != 7 {
		t.Fatalf("want 7 crates, got %d", len(comps))
	}
	for _, c := range comps {
		if c.Scope == sbom.ScopeDevelopment {
			t.Errorf("without a companion Cargo.toml nothing should be dev-scoped: %+v", c)
		}
	}
}

// TestCargoEdgesInlineAndDedup locks the two edge-parity fixes: a populated INLINE `dependencies = […]`
// array is parsed (not dropped), and DependsOn de-dups duplicate targets + filters self-edges (Syft parity).
func TestCargoEdgesInlineAndDedup(t *testing.T) {
	const lock = `[[package]]
name = "app"
version = "1.0.0"
dependencies = ["leaf", "leaf", "app 1.0.0"]

[[package]]
name = "leaf"
version = "2.0.0"
`
	_, deps, err := Cargo{}.Parse(context.Background(), ParseInput{Path: "Cargo.lock", Content: []byte(lock)})
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	edges := map[string][]string{}
	for _, d := range deps {
		edges[d.Ref] = d.DependsOn
	}
	// inline array parsed; duplicate "leaf" deduped; self-ref "app 1.0.0" dropped -> exactly [leaf@2.0.0]
	if on := edges["pkg:cargo/app@1.0.0"]; len(on) != 1 || on[0] != "pkg:cargo/leaf@2.0.0" {
		t.Fatalf("app edges = %v, want [leaf@2.0.0] (inline parsed, dup + self filtered)", on)
	}
}
