package ownsbom

import (
	"context"
	"testing"

	"github.com/KKloudTarus/synapse-ce/internal/domain/sbom"
)

const pubspecLockFixture = `# Generated by pub
packages:
  http:
    dependency: "direct main"
    description:
      name: http
      url: "https://pub.dev"
    source: hosted
    version: "0.13.5"
  lints:
    dependency: "direct dev"
    source: hosted
    version: "2.0.0"
  meta:
    dependency: transitive
    version: "1.8.0"
  flutter:
    dependency: "direct main"
    source: sdk
    version: "0.0.0"
sdks:
  dart: ">=2.17.0 <3.0.0"
`

func TestDartParse(t *testing.T) {
	comps, deps, err := Dart{}.Parse(context.Background(), ParseInput{Path: "pubspec.lock", Content: []byte(pubspecLockFixture)})
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if deps != nil {
		t.Errorf("edges deferred; want nil deps, got %v", deps)
	}
	byName := map[string]sbom.Component{}
	for _, c := range comps {
		byName[c.Name] = c
	}
	if len(comps) != 3 {
		t.Fatalf("want 3 packages (http, lints, meta – flutter SDK pseudo-package skipped), got %d (%+v)", len(comps), comps)
	}
	if _, ok := byName["flutter"]; ok {
		t.Error("a source: sdk pseudo-package (flutter) must be skipped, not emitted as pkg:pub/flutter@0.0.0")
	}
	// http (direct main) → production; its version comes from the indent-4 `version:`, NOT the indent-6
	// `description:` sub-map (which must be ignored – no phantom "name"/"url" packages either).
	if c := byName["http"]; c.PURL != "pkg:pub/http@0.13.5" || c.Scope == sbom.ScopeDevelopment {
		t.Errorf("http should be a production package at 0.13.5: %+v", c)
	}
	if _, ok := byName["name"]; ok {
		t.Error("the indent-6 description sub-map must not leak in as a package")
	}
	if c := byName["lints"]; c.Scope != sbom.ScopeDevelopment {
		t.Errorf("lints (direct dev) should be development-scoped: %+v", c)
	}
	if c := byName["meta"]; c.Scope == sbom.ScopeDevelopment || c.Version != "1.8.0" {
		t.Errorf("meta (transitive) should be production at 1.8.0: %+v", c)
	}
}

func TestDartParseEmpty(t *testing.T) {
	comps, _, err := Dart{}.Parse(context.Background(), ParseInput{Path: "pubspec.lock", Content: []byte("# empty\nsdks:\n  dart: \">=2.0.0\"\n")})
	if err != nil || len(comps) != 0 {
		t.Errorf("a lock with no packages block → no components, no error; got %d, err=%v", len(comps), err)
	}
}
