package ownsbom

import (
	"context"
	"testing"

	"github.com/KKloudTarus/synapse-ce/internal/domain/sbom"
)

const poetryLockFixture = `# This file is automatically @generated by Poetry.

[[package]]
name = "requests"
version = "2.31.0"
description = "Python HTTP for Humans."
category = "main"
optional = false
files = [
    {file = "requests-2.31.0-py3-none-any.whl", hash = "sha256:reqwhlhash"},
    {file = "requests-2.31.0.tar.gz", hash = "sha256:reqtarhash"},
]

[package.dependencies]
charset-normalizer = ">=2,<4"
idna = ">=2.5,<4"

[[package]]
name = "Pytest"
version = "8.0.0"
category = "dev"
optional = false

[[package]]
name = "charset-normalizer"
version = "3.3.2"
category = "main"
`

func TestPoetryParse(t *testing.T) {
	comps, deps, err := Poetry{}.Parse(context.Background(), ParseInput{Path: "poetry.lock", Content: []byte(poetryLockFixture)})
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	// Edges: requests' [package.dependencies] resolves charset-normalizer (it has its own [[package]])
	// but NOT idna (no [[package]] entry → no edge). pytest + charset-normalizer have no [package.dependencies].
	if len(deps) != 1 {
		t.Fatalf("want exactly 1 edge-set (requests), got %d: %+v", len(deps), deps)
	}
	if deps[0].Ref != "pkg:pypi/requests@2.31.0" {
		t.Errorf("edge ref = %q, want pkg:pypi/requests@2.31.0", deps[0].Ref)
	}
	if len(deps[0].DependsOn) != 1 || deps[0].DependsOn[0] != "pkg:pypi/charset-normalizer@3.3.2" {
		t.Errorf("requests must depend on charset-normalizer@3.3.2 only (idna unresolved → no edge), got %v", deps[0].DependsOn)
	}
	if len(comps) != 3 {
		t.Fatalf("want 3 components, got %d: %+v", len(comps), comps)
	}
	byName := map[string]sbom.Component{}
	for _, c := range comps {
		byName[c.Name] = c
	}
	// resolved version + PURL; category "main" -> production. The [package.dependencies] sub-table keys
	// (charset-normalizer/idna as RANGES) must NOT be emitted as components.
	if c := byName["requests"]; c.Version != "2.31.0" || c.PURL != "pkg:pypi/requests@2.31.0" || c.Scope != sbom.ScopeProduction {
		t.Errorf("requests = %+v, want 2.31.0 / pkg:pypi/requests@2.31.0 / production", c)
	}
	// lock v2.0 per-package `files = [...]`: the FIRST artifact hash is captured as a SHA256 Checksum, and the
	// `[package.dependencies]` block that follows the files array still parses (charset-normalizer edge above).
	if ck := byName["requests"].Checksums; len(ck) != 1 || ck[0].Algorithm != "SHA256" || ck[0].Value != "reqwhlhash" {
		t.Errorf("requests checksum = %+v, want [{SHA256 reqwhlhash}]", ck)
	}
	if len(byName["pytest"].Checksums) != 0 {
		t.Errorf("pytest has no files block, want no checksum, got %+v", byName["pytest"].Checksums)
	}
	// category "dev" -> development scope; name PEP 503-normalized (Pytest -> pytest)
	if c := byName["pytest"]; c.Version != "8.0.0" || c.Scope != sbom.ScopeDevelopment {
		t.Errorf("pytest = %+v, want 8.0.0 / dev / normalized name", c)
	}
	// charset-normalizer is emitted via its OWN [[package]] (resolved), not as the requests sub-table key
	if c := byName["charset-normalizer"]; c.Version != "3.3.2" {
		t.Errorf("charset-normalizer should come from its own [[package]] @3.3.2, got %+v", c)
	}
	// idna appears only as a sub-table dependency range (no [[package]]) -> not a component
	if _, ok := byName["idna"]; ok {
		t.Error("a [package.dependencies] range key (idna) must not be emitted as a component")
	}
}

// An unterminated v2 files array (missing `]`) must not swallow the packages that follow it – the next
// [[package]] boundary ends the array, so no component is silently dropped.
func TestPoetryParseUnterminatedFilesArray(t *testing.T) {
	lock := `[[package]]
name = "first"
version = "1.0.0"
files = [
    {file = "first-1.0.0.tar.gz", hash = "sha256:firsthash"},

[[package]]
name = "second"
version = "2.0.0"
`
	comps, _, err := Poetry{}.Parse(context.Background(), ParseInput{Path: "poetry.lock", Content: []byte(lock)})
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	byName := map[string]sbom.Component{}
	for _, c := range comps {
		byName[c.Name] = c
	}
	if _, ok := byName["second"]; !ok {
		t.Fatalf("the package after an unterminated files array must still be emitted, got %+v", comps)
	}
	if ck := byName["first"].Checksums; len(ck) != 1 || ck[0].Value != "firsthash" {
		t.Errorf("first should still get its captured hash, got %+v", ck)
	}
}

// Lock v1 (< 2.0) stores artifact hashes in a trailing [metadata.files] table keyed by package name, not in
// each package's own files array. The hash must still be attached to the matching component.
func TestPoetryParseV1MetadataFiles(t *testing.T) {
	lock := `[[package]]
name = "Requests"
version = "2.31.0"
category = "main"

[metadata]
lock-version = "1.1"
content-hash = "abc"

[metadata.files]
requests = [
    {file = "requests-2.31.0-py3-none-any.whl", hash = "sha256:v1whlhash"},
    {file = "requests-2.31.0.tar.gz", hash = "sha256:v1tarhash"},
]
`
	comps, _, err := Poetry{}.Parse(context.Background(), ParseInput{Path: "poetry.lock", Content: []byte(lock)})
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if len(comps) != 1 {
		t.Fatalf("want 1 component, got %d", len(comps))
	}
	// The [metadata.files] key "requests" (PEP 503-normalized) matches the "Requests" package; first hash wins.
	if ck := comps[0].Checksums; len(ck) != 1 || ck[0].Algorithm != "SHA256" || ck[0].Value != "v1whlhash" {
		t.Errorf("v1 [metadata.files] hash must attach to the component, got %+v", ck)
	}
}

// A dep serialized as a multi-line inline-table array: the key line `tomli = [` resolves the edge, while
// the `{...}` continuation lines + the closing `]` must NOT be harvested as false dependency keys.
func TestPoetryParseMultiLineArrayDep(t *testing.T) {
	lock := `[[package]]
name = "pkg"
version = "1.0.0"
category = "main"

[package.dependencies]
tomli = [
    {version = ">=1.1.0", markers = "python_version < \"3.11\""},
]

[[package]]
name = "tomli"
version = "2.0.1"
category = "main"
`
	_, deps, err := Poetry{}.Parse(context.Background(), ParseInput{Path: "poetry.lock", Content: []byte(lock)})
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if len(deps) != 1 || deps[0].Ref != "pkg:pypi/pkg@1.0.0" {
		t.Fatalf("want one edge-set rooted at pkg, got %+v", deps)
	}
	if len(deps[0].DependsOn) != 1 || deps[0].DependsOn[0] != "pkg:pypi/tomli@2.0.1" {
		t.Errorf("the array dep must resolve to tomli only (no false keys from {...}/]), got %v", deps[0].DependsOn)
	}
}

// A (crafted) lock whose two [[package]] blocks normalize to the SAME name makes that name ambiguous, so an
// edge to it is DROPPED (never guess which version) – mirroring the Cargo resolver.
func TestPoetryParseAmbiguousDepNoEdge(t *testing.T) {
	lock := `[[package]]
name = "app"
version = "1.0.0"
category = "main"

[package.dependencies]
dup-pkg = ">=1"

[[package]]
name = "dup-pkg"
version = "1.0.0"
category = "main"

[[package]]
name = "dup_pkg"
version = "2.0.0"
category = "main"
`
	_, deps, err := Poetry{}.Parse(context.Background(), ParseInput{Path: "poetry.lock", Content: []byte(lock)})
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	// dup-pkg and dup_pkg both PEP 503-normalize to "dup-pkg" → 2 versions → ambiguous → app gets no edge.
	if len(deps) != 0 {
		t.Errorf("an ambiguous duplicate-name dep must yield no edge, got %+v", deps)
	}
}
