// Package shared holds value objects and errors common to all domain packages.
// It must not import any other internal package (innermost layer of the onion).
package shared

import (
	"errors"
	"time"
)

// ID is a domain identifier (opaque string; generated by the platform layer).
type ID string

func (id ID) String() string { return string(id) }
func (id ID) IsZero() bool   { return id == "" }

// Severity is the normalized severity scale shared by findings and vulnerabilities.
type Severity string

const (
	SeverityCritical Severity = "critical"
	SeverityHigh     Severity = "high"
	SeverityMedium   Severity = "medium"
	SeverityLow      Severity = "low"
	SeverityInfo     Severity = "info"
	SeverityUnknown  Severity = "unknown"
)

// Sentinel errors mapped to transport status codes by the adapter layer.
var (
	ErrValidation = errors.New("validation error")
	ErrNotFound   = errors.New("not found")
	ErrForbidden  = errors.New("forbidden")        // scope / authorization-window violations
	ErrConflict   = errors.New("conflict")         // optimistic-concurrency version mismatch (lost-update guard)
	ErrSaturated  = errors.New("system saturated") // bounded admission rejected (backpressure → 503)
)

// Valid reports whether s is a known severity label.
func (s Severity) Valid() bool {
	switch s {
	case SeverityCritical, SeverityHigh, SeverityMedium, SeverityLow, SeverityInfo, SeverityUnknown:
		return true
	}
	return false
}

// SeverityRank orders severity from unknown (0) to critical (5); used for
// thresholds and tie-breaks.
func SeverityRank(s Severity) int {
	switch s {
	case SeverityCritical:
		return 5
	case SeverityHigh:
		return 4
	case SeverityMedium:
		return 3
	case SeverityLow:
		return 2
	case SeverityInfo:
		return 1
	default:
		return 0
	}
}

// Audit holds common audit timestamps embedded by entities.
type Audit struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	// CreatedBy / UpdatedBy attribute a record to the actor that created / last modified it
	// (ownership). Empty = system/unknown (legacy rows, or write paths not yet wired).
	// Engagements persist these; other record types carry the fields and adopt persistence
	// incrementally – the canonical home so ownership is one shape across the domain.
	CreatedBy string
	UpdatedBy string
}
