import { AlertTriangle, ArrowLeft, CalendarClock, FileUp, FolderGit2, Gauge, GitBranch, Play, ShieldAlert } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { Link, useLocation, useParams } from 'react-router-dom'
import { CodeQualityReportView } from '../components/codequality/CodeQualityReportView'
import { FindingExplorer } from '../components/codequality/FindingExplorer'
import { ProjectActivityView } from '../components/codequality/ProjectActivityView'
import { GateEvidence, GradeBadge } from '../components/codequality/qualityPresentation'
import { Button, Card, EmptyState, ErrorState, InfoNote, Pill, Spinner, cn } from '../components/ui'
import { api } from '../lib/api'
import type { LatestProjectAnalysis, Project, ProjectAnalysis, ProjectAnalysisCursor, ScanJob } from '../lib/types'

export function CodeQualityProject() {
  const { key = '' } = useParams(); const location = useLocation(); const activityPage = location.pathname.endsWith('/activity')
  const startError = (location.state as { analysisStartError?: string } | null)?.analysisStartError
  const [project, setProject] = useState<Project | null | undefined>(undefined); const [job, setJob] = useState<ScanJob | null>(null); const [latest, setLatest] = useState<LatestProjectAnalysis | null>(null)
  const [analyses, setAnalyses] = useState<ProjectAnalysis[]>([]); const [analysisCursor, setAnalysisCursor] = useState<ProjectAnalysisCursor | null>(null); const [loadingOlder, setLoadingOlder] = useState(false)
  const [loadError, setLoadError] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [coverage, setCoverage] = useState<File | null>(null)
  const [gates, setGates] = useState<{ key: string; name: string }[]>([]); const poll = useRef<ReturnType<typeof setInterval> | null>(null)
  function stopPoll() { if (poll.current) clearInterval(poll.current); poll.current = null }
  async function refreshResult() { try { const [next, history] = await Promise.all([api.latestProjectAnalysis(key), api.projectAnalyses(key)]); if (!next) throw new Error('Analysis completed but its result is unavailable'); setLatest(next); setAnalyses(history.items); setAnalysisCursor(history.next) } catch (e) { setError(e instanceof Error ? e.message : 'Failed to load analysis result') } }
  async function loadOlder() { if (!analysisCursor || loadingOlder) return; setLoadingOlder(true); try { const history = await api.projectAnalyses(key, analysisCursor); setAnalyses((current) => [...current, ...history.items]); setAnalysisCursor(history.next) } catch (e) { setError(e instanceof Error ? e.message : 'Failed to load older analyses') } finally { setLoadingOlder(false) } }
  function startPoll() { stopPoll(); poll.current = setInterval(async () => { try { const next = await api.projectAnalysisStatus(key); if (!next) throw new Error('Analysis status is unavailable'); setJob(next); if (next.status === 'running') return; stopPoll(); if (next.status === 'succeeded') await refreshResult(); else setError(next.error || 'Analysis failed') } catch (e) { stopPoll(); setError(e instanceof Error ? e.message : 'Failed to refresh analysis status') } }, 1500) }
  useEffect(() => { let live = true; setProject(undefined); setLoadError(null); setError(startError ?? null); setLatest(null); setAnalyses([]); setAnalysisCursor(null); setJob(null); Promise.all([api.getProject(key), api.projectAnalysisStatus(key), api.latestProjectAnalysis(key), api.projectAnalyses(key)]).then(([nextProject, nextJob, nextLatest, history]) => { if (!live) return; setProject(nextProject); setJob(nextJob); setLatest(nextLatest); setAnalyses(history.items); setAnalysisCursor(history.next); if (nextJob?.status === 'running') startPoll(); else if (nextJob?.status === 'failed') setError(nextJob.error || 'Analysis failed') }).catch((e) => { if (live) setLoadError(e instanceof Error ? e.message : 'Failed to load project') }); return () => { live = false; stopPoll() }; /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [key, startError])
  useEffect(() => { api.listQualityGates().then(setGates).catch(() => setGates([])) }, [])
  async function assignGate(gateId: string) { setError(null); try { setProject(await api.assignProjectGate(key, gateId)) } catch (e) { setError(e instanceof Error ? e.message : 'Failed to assign quality gate') } }
  async function run() { setError(null); try { const next = await api.startProjectAnalysis(key, coverage ?? undefined); setCoverage(null); setJob(next); startPoll() } catch (e) { setError(e instanceof Error ? e.message : 'Failed to start analysis') } }
  if (loadError && project === undefined) return <div className="mx-auto max-w-6xl space-y-3"><ErrorState message={loadError} /><Link to="/code-quality" className="inline-flex items-center gap-1.5 text-sm text-branddim hover:underline"><ArrowLeft className="size-4" aria-hidden="true" /> All projects</Link></div>
  if (project === undefined) return <Spinner label="Loading project…" />
  if (!project) return null
  const running = job?.status === 'running'; const status = running ? 'Analyzing' : job?.status === 'failed' ? 'Failed' : latest ? 'Analyzed' : 'Not analyzed'; const latestSnapshot = latest?.analysis ?? null
  return <div className="mx-auto max-w-7xl animate-fade-in">
    <Link to="/code-quality" className="mb-4 inline-flex items-center gap-1.5 text-sm text-mutedfg transition-colors hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand/50"><ArrowLeft className="size-4" aria-hidden="true" /> All projects</Link>
    <header className="bg-hero mb-6 rounded-xl border border-border p-6"><div className="flex flex-wrap items-start justify-between gap-5"><div className="min-w-0"><div className="mb-2 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.14em] text-branddim"><Gauge className="size-4" aria-hidden="true" />Code Quality project</div><h1 className="truncate text-3xl font-bold tracking-tight">{project.name}</h1><p className="mt-1.5 font-mono text-sm text-mutedfg">{project.key}</p></div><div className="flex max-w-xl flex-wrap items-center justify-end gap-2"><Pill className="shrink-0 bg-elevated ring-1 ring-inset ring-border"><Gauge className="size-3" aria-hidden="true" /> {status}</Pill><label className={cn('inline-flex cursor-pointer items-center gap-2 rounded-lg border border-border bg-bg px-3 py-2 text-sm focus-within:ring-2 focus-within:ring-brand/60', coverage ? 'text-foreground' : 'text-mutedfg')} title={coverage?.name ?? 'Optional LCOV, Cobertura, or JaCoCo report'}><FileUp className="size-4" aria-hidden="true" /><span className="max-w-48 truncate">{coverage ? coverage.name : 'Attach coverage'}</span><input aria-label="Coverage report (optional)" className="sr-only" type="file" accept=".info,.lcov,.xml,text/plain,application/xml,text/xml" disabled={running} onChange={(event) => setCoverage(event.target.files?.[0] ?? null)} /></label><Button variant="brand" loading={running} disabled={running} onClick={run}><Play className="size-4" aria-hidden="true" />{latest ? 'Run again' : 'Run analysis'}</Button></div></div>
      <dl className="mt-5 grid grid-cols-1 gap-4 border-t border-border pt-4 text-sm md:grid-cols-3"><div className="min-w-0"><dt className="text-[10px] font-semibold uppercase tracking-[0.12em] text-subtlefg">Source</dt><dd className="mt-1.5 flex min-w-0 items-center gap-2 text-foreground"><FolderGit2 className="size-4 shrink-0 text-mutedfg" aria-hidden="true" /><span className="capitalize">{project.sourceBinding.kind}</span><span className="truncate font-mono text-xs" title={project.sourceBinding.value}>{project.sourceBinding.value}</span></dd></div><div><dt className="flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-[0.12em] text-subtlefg">Quality policy for future runs <InfoNote label="About quality policies">Repository policy uses <code>.synapse-gate.yaml</code> when present and falls back to Synapse way. Selecting a named policy ignores the repository policy. Previous analysis decisions remain unchanged.</InfoNote></dt><dd className="mt-1.5"><select aria-label="Quality gate" value={project.gateId} disabled={running} onChange={(event) => assignGate(event.target.value)} className="h-8 rounded border border-border bg-bg px-2 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-brand/60"><option value="">Repository policy (fallback: Synapse way)</option>{gates.map((gate) => <option key={gate.key} value={gate.key}>{gate.name}</option>)}</select></dd></div><div><dt className="text-[10px] font-semibold uppercase tracking-[0.12em] text-subtlefg">Branch / commit</dt><dd className="mt-1.5 flex items-center gap-2 font-mono text-xs text-foreground"><GitBranch className="size-4 shrink-0 text-mutedfg" aria-hidden="true" />{latestSnapshot?.sourceCommit?.slice(0, 12) || project.sourceBinding.ref || 'Default branch'}</dd></div></dl>
      {running && <div className="mt-5"><div className="mb-1.5 flex items-center justify-between text-xs"><span className="capitalize text-foreground">{job.stage || 'starting'}…</span><span className="font-mono tabular-nums text-mutedfg">{job.progress}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-elevated"><div className="h-full rounded-full bg-brand transition-[width] duration-500" style={{ width: `${Math.max(3, job.progress)}%` }} /></div></div>}
    </header>
    <nav className="mb-6 flex gap-4 border-b border-border" aria-label="Project views"><TabLink to={`/code-quality/projects/${encodeURIComponent(key)}`} active={!activityPage}>Latest analysis</TabLink><TabLink to={`/code-quality/projects/${encodeURIComponent(key)}/activity`} active={activityPage}>Activity</TabLink></nav>
    {error && <div className="mb-6"><ErrorState message={error} /></div>}
    {activityPage ? <ProjectActivityView analyses={analyses} hasOlder={analysisCursor !== null} loadingOlder={loadingOlder} onLoadOlder={loadOlder} /> : <LatestAnalysisView latest={latest} running={running} />}
  </div>
}

function LatestAnalysisView({ latest, running }: { latest: LatestProjectAnalysis | null; running: boolean }) {
  if (!latest) return <Card title="Analysis"><EmptyState icon={running ? Gauge : ShieldAlert} title={running ? 'Analysis in progress' : 'No analyses yet'} hint={running ? 'Source acquisition and the unified quality + security pipeline are running.' : 'Run the project analysis to establish a baseline, evaluate the gate, and unlock trend history.'} /></Card>
  const { analysis: snapshot, result: scan } = latest
  const coverage = snapshot.coverage && snapshot.coverage.totalLines > 0 ? 100 * snapshot.coverage.coveredLines / snapshot.coverage.totalLines : null
  const duplication = snapshot.duplication.totalLines > 0 ? 100 * snapshot.duplication.duplicatedLines / snapshot.duplication.totalLines : 0
  return <div className="space-y-6">
    <Card title="Quality gate decision" className={snapshot.gate.passed ? 'border-low/25' : 'border-critical/30'}><GateEvidence gate={snapshot.gate} info={snapshot.gateInfo} /></Card>
    <div className="grid gap-6 xl:grid-cols-[1fr_1.25fr]"><Card title="New Code period" actions={<Pill>{snapshot.delta ? 'Compared with previous' : 'First baseline'}</Pill>}><p className="text-sm text-mutedfg">{snapshot.delta ? `Changes since analysis ${snapshot.newCode.previousId.slice(0, 12)}. Material escalation and reactivation count as New Code.` : 'First analysis: every current publishable issue is treated as New Code; no comparison delta is available.'}</p><div className="mt-4 grid grid-cols-3 gap-3"><HealthMetric label="New issues" value={snapshot.newCode.counts.total} /><HealthMetric label="New critical" value={snapshot.newCode.counts.bySeverity.critical ?? 0} /><HealthMetric label="New high" value={snapshot.newCode.counts.bySeverity.high ?? 0} /></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><GradeBadge compact label="Security" grade={snapshot.newCode.rating.security} /><GradeBadge compact label="Reliability" grade={snapshot.newCode.rating.reliability} /></div><p className="mt-3 text-xs text-mutedfg">New Code maintainability is unavailable until source-diff changed lines are measured.</p></Card>
      <Card title="Overall health" actions={<span className="flex items-center gap-1.5 text-xs text-mutedfg"><CalendarClock className="size-3.5" aria-hidden="true" />{formatDate(snapshot.createdAt)}</span>}><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><HealthMetric label="Issues" value={withDelta(snapshot.issues.total, snapshot.delta?.issues.total)} /><HealthMetric label="Coverage" value={coverage === null ? 'Not supplied' : `${coverage.toFixed(1)}%`} /><HealthMetric label="Duplication" value={`${duplication.toFixed(1)}%`} hint={snapshot.delta ? `${signed(snapshot.delta.measures.duplication_density ?? 0)}% vs previous` : undefined} /><HealthMetric label="Code lines" value={snapshot.rating.linesOfCode.toLocaleString()} /></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><GradeBadge compact label="Security" grade={snapshot.rating.security} /><GradeBadge compact label="Reliability" grade={snapshot.rating.reliability} /><GradeBadge compact label="Maintainability" grade={snapshot.rating.maintainability} /></div></Card></div>
    <Card title="Security analysis"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><HealthMetric label="Findings" value={scan.findings.length} /><HealthMetric label="Vulnerabilities" value={scan.vulnerabilities.length} /><HealthMetric label="Packages" value={scan.components.length} /><HealthMetric label="License issues" value={scan.licenses.filter((license) => license.verdict !== 'allow').length} /></div>{scan.completeness.warning && <p className="mt-4 flex items-start gap-2 text-xs text-medium"><AlertTriangle className="mt-0.5 size-4 shrink-0" aria-hidden="true" />{scan.completeness.warning}</p>}</Card>
    <FindingExplorer findings={scan.findings} />
    <CodeQualityReportView report={scan.codeQuality} empty={<Card title="Code quality"><EmptyState icon={ShieldAlert} title="Code quality unavailable" hint="This completed scan did not produce a code-quality report." /></Card>} />
  </div>
}

function TabLink({ to, active, children }: { to: string; active: boolean; children: React.ReactNode }) { return <Link to={to} aria-current={active ? 'page' : undefined} className={cn('border-b-2 px-1 pb-2 text-sm font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand/60', active ? 'border-brand text-foreground' : 'border-transparent text-mutedfg')}>{children}</Link> }
function HealthMetric({ label, value, hint }: { label: string; value: string | number; hint?: string }) { return <div className="rounded-lg border border-border bg-bg px-4 py-3"><div className="font-mono text-xl font-semibold tabular-nums">{value}</div><div className="text-xs text-mutedfg">{label}</div>{hint && <div className="mt-1 text-[10px] text-subtlefg">{hint}</div>}</div> }
function withDelta(value: number, delta?: number) { return delta === undefined ? value.toLocaleString() : `${value.toLocaleString()} (${signed(delta)})` }
function signed(value: number) { return value > 0 ? `+${Number(value.toFixed(2))}` : String(Number(value.toFixed(2))) }
function formatDate(value: string) { return new Date(value).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' }) }
