import { Pencil, Plus, ShieldCheck, Trash2, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { api } from '../lib/api'
import type { QualityGate, QualityGateCondition } from '../lib/types'
import { metricLabel } from '../components/codequality/qualityPresentation'
import { Button, Card, EmptyState, ErrorState, Field, Input, Pill, Select, Spinner } from '../components/ui'

const metrics = ['new_critical', 'new_high', 'new_medium', 'new_secret', 'new_vulnerability', 'new_issues', 'total_critical', 'coverage', 'new_coverage', 'duplication_density', 'new_duplication', 'security_rating', 'reliability_rating', 'maintainability_rating', 'security_hotspots_reviewed', 'new_security_hotspots_reviewed']
const operators: QualityGateCondition['op'][] = ['<=', '>=', '==', '<', '>']
const blankCondition = (): QualityGateCondition => ({ metric: 'new_high', op: '<=', threshold: 0 })

export function QualityGates() {
  const [gates, setGates] = useState<QualityGate[] | null>(null); const [error, setError] = useState<string | null>(null); const [editing, setEditing] = useState<QualityGate | 'new' | null>(null)
  function load() { setError(null); api.listQualityGates().then(setGates).catch((e) => setError(e instanceof Error ? e.message : 'Failed to load quality gates')) }
  useEffect(load, [])
  async function remove(gate: QualityGate) { if (!window.confirm(`Delete “${gate.name}”? Assigned gates cannot be deleted.`)) return; setError(null); try { await api.deleteQualityGate(gate.key); if (editing !== 'new' && editing?.key === gate.key) setEditing(null); load() } catch (e) { setError(e instanceof Error ? e.message : 'Failed to delete quality gate') } }
  return <div className="mx-auto max-w-7xl animate-fade-in">
    <header className="bg-hero mb-6 flex flex-wrap items-center justify-between gap-4 rounded-xl border border-border p-6"><div><div className="mb-2 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.14em] text-branddim"><ShieldCheck className="size-4" aria-hidden="true" />Policy</div><h1 className="text-3xl font-bold tracking-tight">Quality Gates</h1><p className="mt-1.5 max-w-2xl text-sm text-mutedfg">Define measurable release policy once, assign it to Projects, and preserve condition-level evidence in every analysis.</p></div><Button variant="brand" onClick={() => setEditing(editing === 'new' ? null : 'new')}>{editing === 'new' ? <><X className="size-4" aria-hidden="true" /> Cancel</> : <><Plus className="size-4" aria-hidden="true" /> New gate</>}</Button></header>
    {editing && <GateEditor key={editing === 'new' ? 'new' : editing.key} gate={editing === 'new' ? null : editing} onCancel={() => setEditing(null)} onSaved={() => { setEditing(null); load() }} />}
    {error && <div className="mb-6"><ErrorState message={error} /><Button className="mt-3" variant="secondary" onClick={load}>Retry</Button></div>}
    {!gates && !error && <Spinner label="Loading quality gates…" />}
    {gates?.length === 0 && <EmptyState icon={ShieldCheck} title="No quality gates" hint="Create a custom gate or use the built-in default." />}
    {gates && gates.length > 0 && <div className="grid gap-4 lg:grid-cols-2">{gates.map((gate) => <Card key={gate.key} title={gate.name} actions={<Pill className="tabular-nums">{gate.builtIn ? 'Built-in' : 'Custom'} · {gate.conditions.length} conditions</Pill>} className={gate.builtIn ? 'border-brand/20' : undefined}><p className="font-mono text-xs text-mutedfg">{gate.key}</p><ul className="mt-4 space-y-2">{gate.conditions.map((condition, index) => <li key={`${condition.metric}-${index}`} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border bg-bg px-3 py-2.5"><span className="text-sm font-medium">{metricLabel(condition.metric)}</span><span className="font-mono tabular-nums text-xs text-mutedfg">{condition.op} {condition.threshold}</span></li>)}</ul>{gate.builtIn ? <p className="mt-4 text-xs text-mutedfg">Synapse maintains this policy. Duplicate its conditions into a custom gate when your release criteria differ.</p> : <div className="mt-4 flex gap-2"><Button variant="secondary" onClick={() => setEditing(gate)}><Pencil className="size-4" aria-hidden="true" /> Edit</Button><Button variant="secondary" onClick={() => remove(gate)}><Trash2 className="size-4" aria-hidden="true" /> Delete</Button></div>}</Card>)}</div>}
  </div>
}

function GateEditor({ gate, onCancel, onSaved }: { gate: QualityGate | null; onCancel: () => void; onSaved: () => void }) {
  const [key, setKey] = useState(gate?.key ?? ''); const [name, setName] = useState(gate?.name ?? ''); const [conditions, setConditions] = useState<QualityGateCondition[]>(gate?.conditions.map((condition) => ({ ...condition })) ?? [blankCondition()]); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false)
  function update(index: number, next: Partial<QualityGateCondition>) { setConditions((current) => current.map((condition, i) => i === index ? { ...condition, ...next } : condition)) }
  async function submit(event: React.FormEvent) { event.preventDefault(); const cleanName = name.trim(); const cleanKey = key.trim(); if (!cleanName || !cleanKey) { setError('Name and key are required.'); return } if (conditions.length === 0) { setError('Add at least one condition.'); return } if (conditions.some((condition) => !Number.isFinite(condition.threshold))) { setError('Every threshold must be a finite number.'); return } setSaving(true); setError(null); try { if (gate) await api.updateQualityGate(gate.key, { name: cleanName, conditions }); else await api.createQualityGate({ key: cleanKey, name: cleanName, conditions }); onSaved() } catch (e) { setError(e instanceof Error ? e.message : 'Failed to save quality gate') } finally { setSaving(false) } }
  return <Card title={gate ? `Edit ${gate.name}` : 'New quality gate'} className="mb-6"><form className="space-y-5" onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><Field label="Name" htmlFor="gate-name"><Input id="gate-name" value={name} onChange={(event) => setName(event.target.value)} autoFocus /></Field><Field label="Key" hint={gate ? 'A gate key is immutable after creation.' : 'Lowercase letters, numbers, and hyphens'} htmlFor="gate-key"><Input id="gate-key" value={key} disabled={!!gate} onChange={(event) => setKey(event.target.value)} /></Field></div><fieldset><div className="mb-3 flex items-center justify-between gap-3"><legend className="font-medium">Conditions</legend><Button type="button" variant="secondary" onClick={() => setConditions((current) => [...current, blankCondition()])}><Plus className="size-4" aria-hidden="true" /> Add condition</Button></div><div className="space-y-3">{conditions.map((condition, index) => <div key={index} className="grid items-end gap-3 rounded-lg border border-border bg-bg p-3 sm:grid-cols-[1fr_8rem_10rem_auto]"><Field label={`Metric ${index + 1}`} htmlFor={`gate-metric-${index}`}><Select id={`gate-metric-${index}`} value={condition.metric} onValueChange={(value) => update(index, { metric: value })} ariaLabel={`Condition ${index + 1} metric`} options={metrics.map((value) => ({ value, label: metricLabel(value) }))} /></Field><Field label="Operator" htmlFor={`gate-op-${index}`}><Select id={`gate-op-${index}`} value={condition.op} onValueChange={(value) => update(index, { op: value as QualityGateCondition['op'] })} ariaLabel={`Condition ${index + 1} operator`} options={operators.map((value) => ({ value, label: value }))} /></Field><Field label="Threshold" htmlFor={`gate-threshold-${index}`}><Input id={`gate-threshold-${index}`} type="number" step="any" value={condition.threshold} onChange={(event) => update(index, { threshold: event.target.value === '' ? Number.NaN : Number(event.target.value) })} /></Field><Button aria-label={`Remove condition ${index + 1}`} type="button" variant="secondary" disabled={conditions.length === 1} onClick={() => setConditions((current) => current.filter((_, i) => i !== index))}><Trash2 className="size-4" aria-hidden="true" /></Button></div>)}</div></fieldset>{error && <ErrorState message={error} />}<div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={onCancel}>Cancel</Button><Button variant="brand" type="submit" loading={saving}>{gate ? 'Save changes' : 'Create gate'}</Button></div></form></Card>
}
