package rulecatalog

import (
	"github.com/KKloudTarus/synapse-ce/internal/domain/rule"
	"github.com/KKloudTarus/synapse-ce/internal/domain/shared"
)

type javaASTRuleSpec struct {
	key, name, cwe, compliant, noncompliant, remediation, description string
	type_                                                             rule.Type
	quality                                                           rule.Quality
	severity                                                          shared.Severity
}

// javaASTRules are the Java structural rules emitted by the synapse-ast tree-sitter sidecar
// (internal/infrastructure/tools/astwalk). They catch multi-line/structural issues a line regex cannot.
func javaASTRules() []rule.Rule {
	specs := []javaASTRuleSpec{
		{"java-ast-empty-method", "Empty method body", "", "void handle() {\n    process(event);\n}", "void handle() {}", "Implement the method, or if it is intentionally empty, add a comment explaining why.", "an empty non-abstract method body", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow},
		{"java-ast-missing-switch-default", "switch without a default", "CWE-478", "switch (state) {\n    case OPEN: open(); break;\n    default: throw new IllegalStateException();\n}", "switch (state) {\n    case OPEN: open(); break;\n}", "Add a default branch (even one that throws) so unhandled values are not silently ignored.", "a switch statement with no default branch", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium},
		{"java-ast-nested-try", "Nested try statement", "", "try {\n    step1();\n    step2();\n} catch (IOException e) {\n    log.warn(\"failed\", e);\n}", "try {\n    try {\n        step1();\n    } finally {\n        cleanup();\n    }\n} catch (IOException e) {\n    log.warn(\"failed\", e);\n}", "Extract the inner try into its own method to flatten the control flow.", "a try statement nested directly inside another try", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow},
		{"java-ast-empty-if-block", "Empty if block", "", "if (ready) {\n    start();\n}", "if (ready) {\n}", "Remove the empty if, or add the intended body.", "an if statement with an empty body", rule.TypeBug, rule.QualityReliability, shared.SeverityLow},
		{"java-ast-collapsible-if", "Collapsible if statement", "", "if (a && b) {\n    run();\n}", "if (a) {\n    if (b) {\n        run();\n    }\n}", "Combine the two conditions with && into a single if.", "an if whose only statement is another if with no else", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow},
		{"java-ast-empty-loop-body", "Empty loop body", "", "for (int i = 0; i < n; i++) {\n    total += data[i];\n}", "for (int i = 0; i < n; i++) {\n}", "Add the intended loop body, or remove the loop.", "a loop with an empty body", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium},
		{"java-ast-too-many-params", "Method has too many parameters", "", "void configure(ServerOptions options) {\n    apply(options);\n}", "void configure(String host, int port, int timeout, boolean tls, String user, String pass, int retries, int backoff) {\n    connect(host, port);\n}", "Group related parameters into a value object or builder.", "a method declared with more than seven parameters", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow},
		{"java-ast-empty-else", "Empty else block", "", "if (ready) {\n    start();\n}", "if (ready) {\n    start();\n} else {\n}", "Remove the empty else branch.", "an else branch with an empty body", rule.TypeBug, rule.QualityReliability, shared.SeverityLow},
		{"java-ast-constant-condition", "Constant if condition", "", "if (enabled) {\n    run();\n}", "if (true) {\n    run();\n}", "Use a real condition, or remove the dead branch.", "an if with a literal true/false condition", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium},
		{"java-ast-nested-ternary", "Nested ternary expression", "", "int tier = base ? 1 : classify(score);", "int tier = base ? 1 : score > 90 ? 3 : 2;", "Use if/else or extract a helper method instead of nesting ternaries.", "a ternary expression nested inside another ternary", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow},
		{"java-ast-long-method", "Overly long method", "", "void process() {\n    stepOne();\n    stepTwo();\n}", "void process() {\n    // more than fifty sequential statements\n    stepOne();\n    stepTwo();\n}", "Split the method into smaller, focused methods.", "a method with an excessive number of statements", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow},
		{"java-ast-identical-branches", "if and else branches are identical", "", "if (found) {\n    save();\n} else {\n    discard();\n}", "if (found) {\n    save();\n} else {\n    save();\n}", "Remove the redundant branch, or fix the branch that is wrong.", "an if whose then and else blocks are identical", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium},
		{"java-ast-if-return-boolean", "if returning boolean literals", "", "return ok;", "if (ok) {\n    return true;\n} else {\n    return false;\n}", "Return the boolean expression directly.", "an if/else that only returns true and false", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow},
		{"java-ast-too-many-returns", "Method has too many return statements", "", "int classify(int x) {\n    return lookup(x);\n}", "int classify(int x) {\n    if (x == 1) return 1;\n    if (x == 2) return 2;\n    if (x == 3) return 3;\n    if (x == 4) return 4;\n    if (x == 5) return 5;\n    if (x == 6) return 6;\n    return 0;\n}", "Reduce the number of exit points; use a lookup or a single result variable.", "a method with many return statements", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow},
		{"java-ast-large-class", "Class has too many methods", "", "class Small {\n    void a() {}\n    void b() {}\n}", "class God {\n    // more than twenty methods\n    void a() {}\n    void b() {}\n}", "Split the class along its distinct responsibilities.", "a class declaring an excessive number of methods", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow},
		{"java-ast-too-many-fields", "Class has too many fields", "", "class Point {\n    int x;\n    int y;\n}", "class God {\n    // more than fifteen fields\n    int a;\n    int b;\n}", "Group related fields into a smaller object, or split the class along its responsibilities.", "a class declaring an excessive number of fields", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow},
		{"java-ast-deep-nesting", "Deeply nested control flow", "", "void handle() {\n    if (!ready) {\n        return;\n    }\n    process();\n}", "void handle() {\n    if (a) {\n        for (int i = 0; i < n; i++) {\n            while (b) {\n                try {\n                    switch (c) {\n                        default: break;\n                    }\n                } finally {\n                    cleanup();\n                }\n            }\n        }\n    }\n}", "Flatten the logic with guard clauses and by extracting nested blocks into methods.", "control flow nested more than four levels deep", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityMedium},
		{"java-ast-nested-loop", "Deeply nested loops", "", "for (int i = 0; i < n; i++) {\n    process(data[i]);\n}", "for (int i = 0; i < n; i++) {\n    for (int j = 0; j < n; j++) {\n        for (int k = 0; k < n; k++) {\n            sum += grid[i][j][k];\n        }\n    }\n}", "Extract inner loops into methods, or rework the algorithm to reduce the nesting.", "three or more loops nested inside one another", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityMedium},
		{"java-ast-complex-condition", "Overly complex boolean condition", "", "if (isEligible(request)) {\n    accept();\n}", "if (a && b && c && d && e && f) {\n    accept();\n}", "Extract the sub-conditions into well-named boolean variables or helper methods.", "a boolean condition combining many && or || operators", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow},
		{"java-ast-high-complexity", "Method has high cyclomatic complexity", "", "int score(Order o) {\n    return table.lookup(o.type());\n}", "int score(Order o) {\n    // many if/else, loops, and && / || branches\n    return computed;\n}", "Reduce the number of decision points by extracting helper methods or using a lookup.", "a method with many decision points (if/loop/case/catch/&& /||)", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityMedium},
		{"java-ast-switch-many-cases", "switch has too many cases", "", "String label(Status s) {\n    return LABELS.get(s);\n}", "switch (status) {\n    // more than fifteen case labels\n    case A: return 1;\n    case B: return 2;\n}", "Model a large case set with a map or polymorphism instead of a long switch.", "a switch statement with a very large number of case labels", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow},
		{"java-ast-useless-catch", "catch clause only rethrows", "", "try {\n    run();\n} catch (IOException e) {\n    log.warn(\"failed\", e);\n    throw e;\n}", "try {\n    run();\n} catch (IOException e) {\n    throw e;\n}", "Remove the redundant try/catch, or actually handle the exception.", "a catch clause whose only statement rethrows the caught exception", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow},
		{"java-ast-unnecessary-else", "Unnecessary else after a jump", "", "int classify(int x) {\n    if (x < 0) {\n        return -1;\n    }\n    return score(x);\n}", "int classify(int x) {\n    if (x < 0) {\n        return -1;\n    } else {\n        return score(x);\n    }\n}", "Drop the else and dedent its body, since the if branch always returns.", "an else after an if branch that always returns or throws", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow},
		{"java-ast-nested-switch", "Nested switch statement", "", "int score(Type t) {\n    return SCORES.get(t);\n}", "switch (outer) {\n    case A:\n        switch (inner) {\n            case X: return 1;\n        }\n}", "Extract the inner switch into its own method.", "a switch statement nested inside another switch", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow},
		{"java-ast-ternary-boolean", "Ternary returning boolean literals", "", "boolean ready = count > 0;", "boolean ready = count > 0 ? true : false;", "Use the condition directly (or its negation) instead of the ternary.", "a ternary whose branches are the literals true and false", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow},
		{"java-ast-param-reassign", "Reassigned method parameter", "", "int add(int base, int extra) {\n    int total = base + extra;\n    return total;\n}", "int add(int base, int extra) {\n    base = base + extra;\n    return base;\n}", "Assign to a local variable instead of the parameter.", "an assignment to a method parameter", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow},
		{"java-ast-small-switch", "switch with very few cases", "", "if (state == OPEN) {\n    open();\n} else {\n    close();\n}", "switch (state) {\n    case OPEN: open(); break;\n    default: close();\n}", "Use an if/else for one or two cases.", "a switch statement with only one or two cases", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow},
		{"java-ast-self-assign", "Self assignment", "", "this.count = count;", "count = count;", "Remove the no-op, or assign the intended value (e.g. this.field).", "an assignment of a variable to itself", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium},
		{"java-ast-self-comparison", "Self comparison", "", "if (a == b) {\n    merge();\n}", "if (a == a) {\n    merge();\n}", "Compare against the intended operand.", "a comparison of a value to itself", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium},
		{"java-ast-empty-switch", "Empty switch statement", "", "switch (state) {\n    case OPEN: open(); break;\n}", "switch (state) {\n}", "Remove the empty switch or add the intended cases.", "a switch statement with no cases", rule.TypeBug, rule.QualityReliability, shared.SeverityLow},
		{"java-ast-empty-try", "Empty try block", "", "try {\n    load();\n} catch (IOException e) {\n    log.warn(\"failed\", e);\n}", "try {\n} catch (IOException e) {\n    log.warn(\"failed\", e);\n}", "Remove the empty try, or move the guarded code into it.", "a try statement with an empty body", rule.TypeBug, rule.QualityReliability, shared.SeverityLow},
		{"java-ast-switch-fallthrough", "switch case falls through", "", "switch (n) {\n    case 1:\n        a();\n        break;\n    case 2:\n        b();\n        break;\n}", "switch (n) {\n    case 1:\n        a();\n    case 2:\n        b();\n        break;\n}", "End each case with break/return/throw, or comment the intentional fall-through.", "a non-empty case that falls through to the next case", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium},
		{"java-ast-useless-constructor", "Useless constructor", "", "class Derived extends Base {\n    void greet() {}\n}", "class Derived extends Base {\n    Derived(String name) {\n        super(name);\n    }\n}", "Remove the constructor; the implicit one forwards to super.", "a constructor that only forwards its arguments to super", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow},
		{"java-ast-negated-if-else", "Negated condition with else", "", "if (ready) {\n    start();\n} else {\n    wait();\n}", "if (!ready) {\n    wait();\n} else {\n    start();\n}", "Invert the condition so the positive case comes first, then swap the branches.", "an if with a negated condition and an else branch", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow},
		{"java-ast-duplicate-if-condition", "Duplicate condition in if/else-if chain", "", "if (x == 1) {\n    a();\n} else if (x == 2) {\n    b();\n}", "if (x == 1) {\n    a();\n} else if (x == 1) {\n    b();\n}", "Fix the duplicated condition; the repeated branch is unreachable.", "a repeated condition in an if/else-if chain, making a branch unreachable", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium},
		{"java-ast-if-chain-no-else", "if/else-if chain without a final else", "", "if (x == 1) {\n    a();\n} else if (x == 2) {\n    b();\n} else {\n    other();\n}", "if (x == 1) {\n    a();\n} else if (x == 2) {\n    b();\n}", "Add a closing else (even one that throws) so unhandled cases are explicit.", "an if/else-if chain that has no final else branch", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow},
	}
	rules := make([]rule.Rule, 0, len(specs))
	for _, s := range specs {
		rules = append(rules, rule.Rule{
			Key: rule.Key(s.key), Name: s.name, Language: "Java", Type: s.type_, Qualities: []rule.Quality{s.quality}, DefaultSeverity: s.severity,
			Tags: []string{"java", "ast"}, CWE: optionalCWE(s.cwe), OWASP: []string{},
			Description: "Detects " + s.description + " in Java source.",
			Rationale:   "This rule reports a Java structure that reduces reliability or maintainability, detected on the syntax tree.\n\nSource: https://docs.oracle.com/javase/specs/",
			Remediation: s.remediation, CompliantExample: s.compliant, NoncompliantExample: s.noncompliant, RemediationEffort: 15, Detection: rule.DetectionAST,
		})
	}
	return rules
}
