package rulecatalog

import (
	"github.com/KKloudTarus/synapse-ce/internal/domain/rule"
	"github.com/KKloudTarus/synapse-ce/internal/domain/shared"
)

func misconfigRules() []rule.Rule {
	var rules []rule.Rule
	rules = append(rules, cfnRules()...)
	rules = append(rules, composeRules()...)
	rules = append(rules, dockerfileRules()...)
	rules = append(rules, ghaRules()...)
	rules = append(rules, k8sRules()...)
	rules = append(rules, tfRules()...)
	return rules
}

func cfnRules() []rule.Rule {
	return []rule.Rule{
		{
			Key: "cloudformation-iam-wildcard", Name: "IAM policy grants a wildcard action or resource", Language: "CloudFormation", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium, Tags: []string{"iam", "aws", "wildcard"}, CWE: []string{"CWE-732"}, OWASP: []string{"A01:2021"}, Detection: rule.DetectionAST,
			Description:         "An IAM policy uses a wildcard ('*') in the Action or Resource field, granting excessively broad permissions.",
			Rationale:           "Wildcard permissions violate the principle of least privilege. If the principal is compromised, the attacker gains unrestricted access to the matched AWS services or resources.\n\nSource: https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#grant-least-privilege",
			Remediation:         "Replace the wildcard with specific API actions and ARNs that the principal strictly needs to function.",
			CompliantExample:    "Resources:\n  MyPolicy:\n    Type: AWS::IAM::Policy\n    Properties:\n      PolicyDocument:\n        Statement:\n          - Effect: Allow\n            Action: \"s3:GetObject\"\n            Resource: \"arn:aws:s3:::mybucket/*\"",
			NoncompliantExample: "Resources:\n  MyPolicy:\n    Type: AWS::IAM::Policy\n    Properties:\n      PolicyDocument:\n        Statement:\n          - Effect: Allow\n            Action: \"*\"\n            Resource: \"*\"",
			RemediationEffort:   30,
		},
		{
			Key: "cloudformation-open-security-group", Name: "Security group open to the entire internet", Language: "CloudFormation", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium, Tags: []string{"network", "aws", "firewall"}, CWE: []string{"CWE-284"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "A security group ingress rule allows traffic from the entire internet.",
			Rationale:           "Opening ports to the entire internet exposes the instances to constant automated brute-force attacks and exploitation of known vulnerabilities.\n\nSource: https://cwe.mitre.org/data/definitions/284.html",
			Remediation:         "Restrict the CidrIp to a specific trusted IP range, a corporate VPN subnet, or reference another specific Security Group ID.",
			CompliantExample:    "Resources:\n  MySG:\n    Type: AWS::EC2::SecurityGroup\n    Properties:\n      SecurityGroupIngress:\n        - CidrIp: \"10.0.0.0/8\"",
			NoncompliantExample: "Resources:\n  MySG:\n    Type: AWS::EC2::SecurityGroup\n    Properties:\n      SecurityGroupIngress:\n        - CidrIp: \"0.0.0.0/0\"",
			RemediationEffort:   15,
		},
		{
			Key: "cloudformation-plaintext-secret", Name: "Hardcoded secret in a resource property", Language: "CloudFormation", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh, Tags: []string{"credentials", "aws"}, CWE: []string{"CWE-798"}, OWASP: []string{"A07:2021"}, Detection: rule.DetectionAST,
			Description:         "A plaintext password or secret token is embedded directly in the CloudFormation template.",
			Rationale:           "Hardcoding secrets in infrastructure templates exposes them to anyone who can view the template in version control or the AWS console.\n\nSource: https://cwe.mitre.org/data/definitions/798.html",
			Remediation:         "Use AWS Secrets Manager or Systems Manager Parameter Store with the 'resolve:ssm-secure' dynamic reference syntax to inject the secret at deployment time.",
			CompliantExample:    "Resources:\n  MyDB:\n    Type: AWS::RDS::DBInstance\n    Properties:\n      DBPassword: \"{{resolve:secretsmanager:MySecret:SecretString:password}}\"",
			NoncompliantExample: "Resources:\n  MyDB:\n    Type: AWS::RDS::DBInstance\n    Properties:\n      DBPassword: \"example-password\"",
			RemediationEffort:   15,
		},
		{
			Key: "cloudformation-public-bucket-acl", Name: "S3 bucket granted a public ACL", Language: "CloudFormation", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh, Tags: []string{"s3", "aws", "storage"}, CWE: []string{"CWE-732"}, OWASP: []string{"A01:2021"}, Detection: rule.DetectionAST,
			Description:         "An S3 Bucket is configured with a PublicRead or PublicReadWrite canned ACL.",
			Rationale:           "Public read/write ACLs allow anyone on the internet to view or modify the contents of the bucket, leading to severe data breaches or hosting of malicious content.\n\nSource: https://cwe.mitre.org/data/definitions/732.html",
			Remediation:         "Set AccessControl to 'Private' and manage access via IAM policies or specific Bucket Policies instead of ACLs.",
			CompliantExample:    "Resources:\n  MyBucket:\n    Type: AWS::S3::Bucket\n    Properties:\n      AccessControl: Private",
			NoncompliantExample: "Resources:\n  MyBucket:\n    Type: AWS::S3::Bucket\n    Properties:\n      AccessControl: PublicRead",
			RemediationEffort:   15,
		},
		{
			Key: "cloudformation-rds-unencrypted", Name: "RDS instance storage not encrypted", Language: "CloudFormation", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium, Tags: []string{"rds", "aws", "encryption"}, CWE: []string{"CWE-311"}, OWASP: []string{"A02:2021"}, Detection: rule.DetectionAST,
			Description:         "An RDS DBInstance is provisioned without enabling StorageEncrypted.",
			Rationale:           "Unencrypted storage volumes expose data at rest to physical extraction or unauthorized snapshot access. Compliance frameworks mandate at-rest encryption for datastores.\n\nSource: https://cwe.mitre.org/data/definitions/311.html",
			Remediation:         "Set StorageEncrypted to true. You may optionally provide a KmsKeyId for custom key management.",
			CompliantExample:    "Resources:\n  MyDB:\n    Type: AWS::RDS::DBInstance\n    Properties:\n      StorageEncrypted: true",
			NoncompliantExample: "Resources:\n  MyDB:\n    Type: AWS::RDS::DBInstance\n    Properties:\n      StorageEncrypted: false",
			RemediationEffort:   15,
		},
		{
			Key: "cloudformation-s3-no-encryption", Name: "S3 bucket without default encryption", Language: "CloudFormation", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium, Tags: []string{"s3", "aws", "encryption"}, CWE: []string{"CWE-311"}, OWASP: []string{"A02:2021"}, Detection: rule.DetectionAST,
			Description:         "An S3 Bucket does not configure BucketEncryption to enforce Server-Side Encryption.",
			Rationale:           "While AWS now encrypts new S3 buckets by default, relying on the implicit default without explicit configuration can lead to compliance failures or accidental exposure if defaults change.\n\nSource: https://cwe.mitre.org/data/definitions/311.html",
			Remediation:         "Explicitly declare the BucketEncryption property using AES256 (SSE-S3) or aws:kms (SSE-KMS).",
			CompliantExample:    "Resources:\n  MyBucket:\n    Type: AWS::S3::Bucket\n    Properties:\n      BucketEncryption:\n        ServerSideEncryptionConfiguration:\n          - ServerSideEncryptionByDefault:\n              SSEAlgorithm: AES256",
			NoncompliantExample: "Resources:\n  MyBucket:\n    Type: AWS::S3::Bucket\n    Properties:\n      BucketName: my-bucket",
			RemediationEffort:   15,
		},
	}
}

func composeRules() []rule.Rule {
	return []rule.Rule{
		{
			Key: "compose-dangerous-capability", Name: "Dangerous Linux capability added", Language: "Docker Compose", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh, Tags: []string{"docker", "capabilities"}, CWE: []string{"CWE-269"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionPattern,
			Description:         "The container adds high-risk Linux capabilities like SYS_ADMIN or NET_ADMIN.",
			Rationale:           "Capabilities like SYS_ADMIN are essentially equivalent to root. If the container is compromised, the attacker can use these capabilities to break out of the container isolation.\n\nSource: https://cwe.mitre.org/data/definitions/269.html",
			Remediation:         "Remove the cap_add directive. If a capability is strictly required, ensure it is not a universally privileged one.",
			CompliantExample:    "cap_drop:\n  - ALL",
			NoncompliantExample: "cap_add:\n  - SYS_ADMIN",
			RemediationEffort:   15,
		},
		{
			Key: "compose-docker-socket-mount", Name: "Docker socket mounted into a container", Language: "Docker Compose", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh, Tags: []string{"docker", "mount"}, CWE: []string{"CWE-250"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionPattern,
			Description:         "The host's Docker socket (/var/run/docker.sock) is mounted into the container.",
			Rationale:           "Mounting the Docker socket gives the container complete control over the host's Docker daemon, allowing a compromised container to start new privileged containers and take over the host system.\n\nSource: https://cwe.mitre.org/data/definitions/250.html",
			Remediation:         "Never mount the Docker socket into untrusted containers. Use Docker-in-Docker (DinD) without host mounts or alternative build tools like Kaniko if container building is required.",
			CompliantExample:    "volumes:\n  - /app/data:/data",
			NoncompliantExample: "volumes:\n  - /var/run/docker.sock:/var/run/docker.sock",
			RemediationEffort:   30,
		},
		{
			Key: "compose-host-ipc", Name: "Host IPC namespace", Language: "Docker Compose", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityLow, Tags: []string{"docker", "namespace"}, CWE: []string{"CWE-269"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionPattern,
			Description:         "The container is configured with `ipc: host`.",
			Rationale:           "Sharing the host's IPC namespace allows the container to read or write to memory segments used by host processes, breaking isolation and risking data theft or host disruption.\n\nSource: https://cwe.mitre.org/data/definitions/269.html",
			Remediation:         "Remove the `ipc: host` directive. Allow the container engine to create an isolated IPC namespace.",
			CompliantExample:    "services:\n  web:\n    image: nginx",
			NoncompliantExample: "services:\n  web:\n    image: nginx\n    ipc: host",
			RemediationEffort:   15,
		},
		{
			Key: "compose-host-network", Name: "Host network mode", Language: "Docker Compose", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium, Tags: []string{"docker", "network"}, CWE: []string{"CWE-269"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionPattern,
			Description:         "The container is configured with `network_mode: host`.",
			Rationale:           "Host networking bypasses Docker's network isolation. The container can bind to any host interface and sniff host loopback traffic, increasing the blast radius of a compromise.\n\nSource: https://cwe.mitre.org/data/definitions/269.html",
			Remediation:         "Use standard Docker bridge or overlay networks, and map only required ports using the `ports` directive.",
			CompliantExample:    "ports:\n  - \"8080:80\"",
			NoncompliantExample: "network_mode: host",
			RemediationEffort:   15,
		},
		{
			Key: "compose-host-pid", Name: "Host PID namespace", Language: "Docker Compose", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium, Tags: []string{"docker", "namespace"}, CWE: []string{"CWE-269"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionPattern,
			Description:         "The container is configured with `pid: host`.",
			Rationale:           "Sharing the host PID namespace allows the container to view and potentially signal (kill) host processes, breaking fundamental container process isolation.\n\nSource: https://cwe.mitre.org/data/definitions/269.html",
			Remediation:         "Remove the `pid: host` directive. If container monitoring is needed, use dedicated agents with scoped permissions.",
			CompliantExample:    "services:\n  web:\n    image: nginx",
			NoncompliantExample: "services:\n  web:\n    image: nginx\n    pid: host",
			RemediationEffort:   15,
		},
		{
			Key: "compose-image-unpinned", Name: "Image is not version-pinned", Language: "Docker Compose", Type: rule.TypeBug, Qualities: []rule.Quality{rule.QualityReliability}, DefaultSeverity: shared.SeverityLow, Tags: []string{"docker", "reproducibility"}, CWE: []string{}, OWASP: []string{}, Detection: rule.DetectionPattern,
			Description:         "The service uses an unpinned image tag (no tag, or ':latest').",
			Rationale:           "Using mutable tags like 'latest' breaks reproducibility. Deployments can unexpectedly pull a new, breaking version of the image without any code changes.\n\nSource: https://docs.docker.com/develop/dev-best-practices/",
			Remediation:         "Pin the image to a specific version tag or immutable SHA digest.",
			CompliantExample:    "image: nginx:1.24.0-alpine",
			NoncompliantExample: "image: nginx:latest",
			RemediationEffort:   5,
		},
		{
			Key: "compose-privileged", Name: "Privileged container", Language: "Docker Compose", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh, Tags: []string{"docker", "privilege"}, CWE: []string{"CWE-269"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionPattern,
			Description:         "The service is configured with `privileged: true`.",
			Rationale:           "Privileged mode disables almost all security mechanisms (seccomp, AppArmor, cgroups, capability drops), giving the container full access to host devices. A compromise is equivalent to root on the host.\n\nSource: https://cwe.mitre.org/data/definitions/269.html",
			Remediation:         "Remove `privileged: true`. Grant only the specific capabilities or device mounts required for the application.",
			CompliantExample:    "services:\n  web:\n    image: nginx",
			NoncompliantExample: "services:\n  web:\n    image: nginx\n    privileged: true",
			RemediationEffort:   30,
		},
		{
			Key: "compose-secret-in-env", Name: "Secret hardcoded in environment", Language: "Docker Compose", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium, Tags: []string{"docker", "credentials"}, CWE: []string{"CWE-798"}, OWASP: []string{"A07:2021"}, Detection: rule.DetectionPattern,
			Description:         "A literal secret or password is set in the `environment` dictionary.",
			Rationale:           "Storing secrets in environment variables inside Compose files commits them to version control. Anyone with repo access or server access can read the plaintext secrets.\n\nSource: https://cwe.mitre.org/data/definitions/798.html",
			Remediation:         "Use the `env_file` directive, Docker secrets, or pass variables from the host environment dynamically.",
			CompliantExample:    "environment:\n  - DB_PASSWORD=${DB_PASSWORD}",
			NoncompliantExample: "environment:\n  - DB_PASSWORD=example-password",
			RemediationEffort:   15,
		},
		{
			Key: "compose-unconfined-security-opt", Name: "Container security profile disabled", Language: "Docker Compose", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh, Tags: []string{"docker", "seccomp"}, CWE: []string{"CWE-250"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionPattern,
			Description:         "The service configures `security_opt` to unconfined (e.g., seccomp:unconfined or apparmor:unconfined).",
			Rationale:           "Disabling seccomp or AppArmor removes the kernel-level restrictions on the syscalls the container can make, significantly lowering the barrier for a container breakout exploit.\n\nSource: https://cwe.mitre.org/data/definitions/250.html",
			Remediation:         "Remove the unconfined `security_opt` directive. Let Docker apply the default seccomp profile, or supply a custom profile if needed.",
			CompliantExample:    "services:\n  web:\n    image: nginx",
			NoncompliantExample: "security_opt:\n  - seccomp:unconfined",
			RemediationEffort:   15,
		},
		{
			Key: "compose-userns-host", Name: "User namespace isolation disabled", Language: "Docker Compose", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium, Tags: []string{"docker", "namespace"}, CWE: []string{"CWE-269"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionPattern,
			Description:         "The container is configured with `userns_mode: host`.",
			Rationale:           "Disabling the user namespace mapping means the container's root user is the same as the host's root user, increasing the impact of a file system breakout.\n\nSource: https://cwe.mitre.org/data/definitions/269.html",
			Remediation:         "Remove `userns_mode: host`. Ensure user namespace remapping is active on the Docker daemon.",
			CompliantExample:    "services:\n  web:\n    image: nginx",
			NoncompliantExample: "services:\n  web:\n    image: nginx\n    userns_mode: host",
			RemediationEffort:   15,
		},
	}
}

func dockerfileRules() []rule.Rule {
	return []rule.Rule{
		{
			Key: "dockerfile-add-instead-of-copy", Name: "ADD used for a local file (prefer COPY)", Language: "Dockerfile", Type: rule.TypeCodeSmell, Qualities: []rule.Quality{rule.QualityMaintainability}, DefaultSeverity: shared.SeverityLow, Tags: []string{"docker", "best-practice"}, CWE: []string{}, OWASP: []string{}, Detection: rule.DetectionPattern,
			Description:         "The Dockerfile uses ADD instead of COPY for local files.",
			Rationale:           "ADD automatically extracts archives and can fetch from URLs, which makes the build unpredictable. COPY explicitly copies local files without magic side effects.\n\nSource: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy",
			Remediation:         "Use COPY for all local file inclusions. Only use ADD when auto-extraction of a local tarball is strictly required.",
			CompliantExample:    "COPY src/ /app/src/",
			NoncompliantExample: "ADD src/ /app/src/",
			RemediationEffort:   5,
		},
		{
			Key: "dockerfile-add-remote-url", Name: "ADD fetches a remote URL", Language: "Dockerfile", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium, Tags: []string{"docker", "network"}, CWE: []string{"CWE-494"}, OWASP: []string{"A08:2021"}, Detection: rule.DetectionPattern,
			Description:         "The ADD instruction fetches a remote URL directly.",
			Rationale:           "Using ADD to fetch remote files leaves the downloaded file in an intermediate image layer, increasing image size. Furthermore, it bypasses checksum verification during the fetch.\n\nSource: https://cwe.mitre.org/data/definitions/494.html",
			Remediation:         "Use RUN with curl/wget, verify the checksum of the downloaded file, extract it, and clean up the archive in a single RUN instruction.",
			CompliantExample:    "RUN curl -fsSLo /tmp/file.tar.gz https://example.com/file.tar.gz \\\n && echo \"<sha256>  /tmp/file.tar.gz\" | sha256sum -c - \\\n && tar -xzf /tmp/file.tar.gz -C /app \\\n && rm /tmp/file.tar.gz",
			NoncompliantExample: "ADD https://example.com/file.tar.gz /app/",
			RemediationEffort:   15,
		},
		{
			Key: "dockerfile-apt-no-clean", Name: "apt install without cache cleanup", Language: "Dockerfile", Type: rule.TypeCodeSmell, Qualities: []rule.Quality{rule.QualityMaintainability}, DefaultSeverity: shared.SeverityLow, Tags: []string{"docker", "size"}, CWE: []string{}, OWASP: []string{}, Detection: rule.DetectionPattern,
			Description:         "A RUN instruction invokes apt-get without cleaning up the apt lists.",
			Rationale:           "Failing to run `apt-get clean` and `rm -rf /var/lib/apt/lists/*` inside the same RUN instruction leaves package index files in the image layer, significantly bloating the final image size.\n\nSource: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run",
			Remediation:         "Append `&& rm -rf /var/lib/apt/lists/*` to the end of the apt-get install instruction.",
			CompliantExample:    "RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*",
			NoncompliantExample: "RUN apt-get update && apt-get install -y curl",
			RemediationEffort:   5,
		},
		{
			Key: "dockerfile-image-no-tag", Name: "Base image is not version-pinned", Language: "Dockerfile", Type: rule.TypeBug, Qualities: []rule.Quality{rule.QualityReliability}, DefaultSeverity: shared.SeverityMedium, Tags: []string{"docker", "reproducibility"}, CWE: []string{}, OWASP: []string{}, Detection: rule.DetectionPattern,
			Description:         "The FROM instruction uses an unpinned image tag.",
			Rationale:           "Building from `:latest` makes the build non-deterministic. A future build could pull a newer, incompatible version of the base image and break the application without warning.\n\nSource: https://docs.docker.com/develop/dev-best-practices/",
			Remediation:         "Pin the base image to a specific version or an immutable SHA digest.",
			CompliantExample:    "FROM node:18.16.0-alpine",
			NoncompliantExample: "FROM node:latest",
			RemediationEffort:   5,
		},
		{
			Key:                 "dockerfile-insecure-download",
			Name:                "TLS verification disabled in a download",
			Language:            "Dockerfile",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"docker", "network", "tls"},
			CWE:                 []string{"CWE-295"},
			OWASP:               []string{"A02:2021"},
			Description:         "Detects the use of flags that disable TLS verification during downloads.",
			Rationale:           "Disabling TLS certificate validation allows man-in-the-middle attackers to intercept and spoof the connection, potentially serving malicious binaries or scripts during the container build.\n\nSource: https://cwe.mitre.org/data/definitions/295.html",
			Remediation:         "Remove flags such as '-k', '--insecure', or '--no-check-certificate' to enforce strict TLS validation.",
			CompliantExample:    "RUN curl -sSL -o file.tar.gz https://example.com/file.tar.gz",
			NoncompliantExample: "RUN curl --insecure -sSL -o file.tar.gz https://example.com/file.tar.gz",
			RemediationEffort:   5,
			Detection:           rule.DetectionPattern,
		},
		{
			Key: "dockerfile-no-healthcheck", Name: "No container HEALTHCHECK", Language: "Dockerfile", Type: rule.TypeBug, Qualities: []rule.Quality{rule.QualityReliability}, DefaultSeverity: shared.SeverityLow, Tags: []string{"docker", "health"}, CWE: []string{}, OWASP: []string{}, Detection: rule.DetectionPattern,
			Description:         "The Dockerfile does not specify a HEALTHCHECK.",
			Rationale:           "Without a HEALTHCHECK, the container orchestrator (like Docker Swarm) cannot determine if the application inside the container is actually functioning, leading to traffic routing to dead containers.\n\nSource: https://docs.docker.com/engine/reference/builder/#healthcheck",
			Remediation:         "Add a HEALTHCHECK instruction that periodically checks an application endpoint or runs a diagnostic command.",
			CompliantExample:    "HEALTHCHECK CMD curl --fail http://localhost/health || exit 1",
			NoncompliantExample: "FROM nginx:alpine\nCOPY . /usr/share/nginx/html",
			RemediationEffort:   15,
		},
		{
			Key: "dockerfile-run-as-root", Name: "Container runs as root", Language: "Dockerfile", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh, Tags: []string{"docker", "privilege"}, CWE: []string{"CWE-250"}, OWASP: []string{"A04:2021"}, Detection: rule.DetectionPattern,
			Description:         "The Dockerfile explicitly sets USER root or leaves the default user as root.",
			Rationale:           "Running the container entrypoint as root violates least privilege. If the application is compromised, the attacker has root privileges within the container, making breakouts easier.\n\nSource: https://cwe.mitre.org/data/definitions/250.html",
			Remediation:         "Create a dedicated non-root user and group, change ownership of required files, and set `USER nonroot` before the CMD or ENTRYPOINT.",
			CompliantExample:    "FROM ubuntu\nUSER nobody",
			NoncompliantExample: "FROM ubuntu\nUSER root",
			RemediationEffort:   30,
		},
		{
			Key:                 "dockerfile-run-pipe-shell",
			Name:                "Remote script piped to a shell",
			Language:            "Dockerfile",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"docker", "security", "supply-chain"},
			CWE:                 []string{"CWE-494"},
			OWASP:               []string{"A08:2021"},
			Description:         "Detects downloading a remote script and piping it directly into a shell.",
			Rationale:           "Downloading a script over the network and piping it directly to a shell allows arbitrary code execution. If the download source is compromised or intercepted, malicious code will run as part of the build.\n\nSource: https://cwe.mitre.org/data/definitions/494.html",
			Remediation:         "Download the file, verify its checksum or cryptographic signature, and then execute the verified local file.",
			CompliantExample:    "RUN curl -sSL -o script.sh https://example.com/script.sh && sha256sum -c script.sh.sha256 && bash script.sh",
			NoncompliantExample: "RUN curl -sSL https://example.com/script.sh | bash",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key: "dockerfile-run-sudo", Name: "sudo used in a RUN step", Language: "Dockerfile", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium, Tags: []string{"docker", "privilege"}, CWE: []string{"CWE-250"}, OWASP: []string{"A04:2021"}, Detection: rule.DetectionPattern,
			Description:         "A RUN instruction uses `sudo`.",
			Rationale:           "Using sudo inside a container is an anti-pattern. It unnecessarily requires the sudo binary and often implies the container expects interactive password entry or passwordless escalation, expanding the attack surface.\n\nSource: https://cwe.mitre.org/data/definitions/250.html",
			Remediation:         "Remove sudo. Run the build steps as root and switch to a non-root user via the USER instruction only at the end of the Dockerfile.",
			CompliantExample:    "RUN apt-get install -y curl\nUSER appuser",
			NoncompliantExample: "USER appuser\nRUN sudo apt-get install -y curl",
			RemediationEffort:   15,
		},
		{
			Key: "dockerfile-secret-in-arg", Name: "Secret baked into image (ARG)", Language: "Dockerfile", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh, Tags: []string{"docker", "credentials"}, CWE: []string{"CWE-798"}, OWASP: []string{"A07:2021"}, Detection: rule.DetectionPattern,
			Description:         "An ARG instruction appears to declare a sensitive variable (e.g., TOKEN, PASSWORD).",
			Rationale:           "Build ARGs are permanently baked into the image metadata and can be viewed by anyone who runs `docker history` on the resulting image, leading to secret disclosure.\n\nSource: https://cwe.mitre.org/data/definitions/798.html",
			Remediation:         "Use Docker BuildKit's secret mounting feature (`--mount=type=secret`) to consume secrets during the build without leaving them in the image history.",
			CompliantExample:    "FROM ubuntu\nARG API_TOKEN",
			NoncompliantExample: "FROM ubuntu\nARG API_TOKEN=12345",
			RemediationEffort:   30,
		},
		{
			Key: "dockerfile-secret-in-env", Name: "Secret baked into image (ENV)", Language: "Dockerfile", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh, Tags: []string{"docker", "credentials"}, CWE: []string{"CWE-798"}, OWASP: []string{"A07:2021"}, Detection: rule.DetectionPattern,
			Description:         "An ENV instruction declares a sensitive environment variable.",
			Rationale:           "ENV values persist in the final image's configuration and are visible to anyone with access to the image via `docker inspect`. Never bake secrets into container images.\n\nSource: https://cwe.mitre.org/data/definitions/798.html",
			Remediation:         "Remove the ENV secret. Inject secrets dynamically at runtime using orchestration tools like Kubernetes Secrets or Docker Swarm secrets.",
			CompliantExample:    "# Secrets provided at runtime via orchestrator",
			NoncompliantExample: "ENV DB_PASSWORD=example-password",
			RemediationEffort:   15,
		},
	}
}

func ghaRules() []rule.Rule {
	return []rule.Rule{
		{
			Key: "gha-permissions-write-all", Name: "Workflow grants write-all permissions", Language: "GitHub Actions", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium, Tags: []string{"actions", "permissions"}, CWE: []string{"CWE-732"}, OWASP: []string{"A01:2021"}, Detection: rule.DetectionPattern,
			Description:         "The workflow sets permissions to 'write-all'.",
			Rationale:           "Granting write-all permissions gives the workflow token full access to modify the repository, releases, and packages. If an action is compromised, the attacker can hijack the repository.\n\nSource: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token",
			Remediation:         "Remove `write-all` and explicitly declare only the minimum permissions required for the workflow (e.g., `contents: read`).",
			CompliantExample:    "permissions:\n  contents: read",
			NoncompliantExample: "permissions: write-all",
			RemediationEffort:   15,
		},
		{
			Key: "gha-pull-request-target", Name: "Workflow triggers on pull_request_target", Language: "GitHub Actions", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh, Tags: []string{"actions", "trigger"}, CWE: []string{"CWE-250"}, OWASP: []string{"A04:2021"}, Detection: rule.DetectionPattern,
			Description:         "The workflow runs on the `pull_request_target` trigger.",
			Rationale:           "The pull_request_target trigger runs the workflow with a privileged repository token and access to secrets, even when triggered by a fork. This allows attackers to exfiltrate secrets by submitting a malicious PR.\n\nSource: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/",
			Remediation:         "Use the `pull_request` trigger instead, which runs with a read-only token and no secret access for forks, unless building a specific trusted triage bot.",
			CompliantExample:    "on:\n  pull_request:\n    branches: [main]",
			NoncompliantExample: "on:\n  pull_request_target:\n    branches: [main]",
			RemediationEffort:   15,
		},
		{
			Key: "gha-script-injection", Name: "Untrusted input interpolated into a run script", Language: "GitHub Actions", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh, Tags: []string{"actions", "injection"}, CWE: []string{"CWE-78"}, OWASP: []string{"A03:2021"}, Detection: rule.DetectionPattern,
			Description:         "A run step interpolates GitHub context expressions (like github.event.issue.title) directly into a bash script.",
			Rationale:           "GitHub evaluates expressions before passing the script to bash. If the expression contains bash special characters, an attacker who controls the issue title or PR body can execute arbitrary commands on the runner.\n\nSource: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections",
			Remediation:         "Bind the context expression to a step environment variable and reference the variable in the bash script.",
			CompliantExample:    "env:\n  TITLE: ${{ github.event.issue.title }}\nrun: echo \"$TITLE\"",
			NoncompliantExample: "run: echo \"${{ github.event.issue.title }}\"",
			RemediationEffort:   15,
		},
		{
			Key:                 "gha-unpinned-action",
			Name:                "Third-party action not pinned to a commit SHA",
			Language:            "GitHub Actions",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"github-actions", "supply-chain"},
			CWE:                 []string{"CWE-829"},
			OWASP:               []string{"A08:2021"},
			Description:         "Detects GitHub Actions referencing a branch or tag instead of a specific commit SHA.",
			Rationale:           "Using mutable tags (like `v1` or `master`) for GitHub Actions allows the action author (or an attacker who compromised the action's repository) to silently replace the code being executed in your CI pipeline.\n\nSource: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions",
			Remediation:         "Pin the action to a specific commit SHA.",
			CompliantExample:    "uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3",
			NoncompliantExample: "uses: actions/checkout@v3",
			RemediationEffort:   5,
			Detection:           rule.DetectionPattern,
		},
	}
}

func k8sRules() []rule.Rule {
	return []rule.Rule{
		{
			Key: "kubernetes-allow-priv-escalation", Name: "Privilege escalation allowed", Language: "Kubernetes", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium, Tags: []string{"kubernetes", "privilege"}, CWE: []string{"CWE-269"}, OWASP: []string{"A04:2021"}, Detection: rule.DetectionAST,
			Description:         "The securityContext explicitly sets `allowPrivilegeEscalation: true`.",
			Rationale:           "Allowing privilege escalation means a process inside the container can gain more privileges than its parent (e.g., via setuid binaries), facilitating container breakouts.\n\nSource: https://kubernetes.io/docs/concepts/security/pod-security-standards/",
			Remediation:         "Set `allowPrivilegeEscalation: false` in the container's securityContext.",
			CompliantExample:    "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  securityContext:\n    runAsNonRoot: true\n    runAsUser: 1000\n    runAsGroup: 1000\n    seccompProfile:\n      type: RuntimeDefault\n  containers:\n  - name: test\n    image: test:1.0@sha256:abc\n    resources:\n      limits:\n        cpu: 100m\n        memory: 128Mi\n    securityContext:\n      allowPrivilegeEscalation: false\n      readOnlyRootFilesystem: true\n      capabilities:\n        drop: [\"ALL\"]\n",
			NoncompliantExample: "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  containers:\n  - name: test\n    image: test\n    securityContext:\n      allowPrivilegeEscalation: true\n",
			RemediationEffort:   15,
		},
		{
			Key: "kubernetes-automount-sa-token", Name: "Service-account token auto-mounted", Language: "Kubernetes", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityLow, Tags: []string{"kubernetes", "rbac"}, CWE: []string{"CWE-284"}, OWASP: []string{"A01:2021"}, Detection: rule.DetectionAST,
			Description:         "The Pod automounts the default ServiceAccount token.",
			Rationale:           "Automounting the token gives any attacker who compromises the pod immediate access to the Kubernetes API using the pod's service account, leading to lateral movement.\n\nSource: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/",
			Remediation:         "Set `automountServiceAccountToken: false` on the Pod spec unless the application explicitly needs to communicate with the Kubernetes API.",
			CompliantExample:    "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  securityContext:\n    runAsNonRoot: true\n    runAsUser: 1000\n    runAsGroup: 1000\n    seccompProfile:\n      type: RuntimeDefault\n  containers:\n  - name: test\n    image: test:1.0@sha256:abc\n    resources:\n      limits:\n        cpu: 100m\n        memory: 128Mi\n    securityContext:\n      allowPrivilegeEscalation: false\n      readOnlyRootFilesystem: true\n      capabilities:\n        drop: [\"ALL\"]\n  automountServiceAccountToken: false\n",
			NoncompliantExample: "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  automountServiceAccountToken: true\n  containers:\n  - name: test\n    image: test\n",
			RemediationEffort:   15,
		},
		{
			Key: "kubernetes-caps-not-dropped", Name: "Default Linux capabilities not dropped", Language: "Kubernetes", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityLow, Tags: []string{"kubernetes", "capabilities"}, CWE: []string{"CWE-250"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "The container fails to drop ALL default Linux capabilities.",
			Rationale:           "By default, containers retain several capabilities (like CHOWN or NET_RAW). The principle of least privilege dictates dropping all capabilities and explicitly adding back only the required ones.\n\nSource: https://kubernetes.io/docs/concepts/security/pod-security-standards/",
			Remediation:         "Add a `capabilities` block to the securityContext that drops `ALL`.",
			CompliantExample:    "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  securityContext:\n    runAsNonRoot: true\n    runAsUser: 1000\n    runAsGroup: 1000\n    seccompProfile:\n      type: RuntimeDefault\n  containers:\n  - name: test\n    image: test:1.0@sha256:abc\n    resources:\n      limits:\n        cpu: 100m\n        memory: 128Mi\n    securityContext:\n      allowPrivilegeEscalation: false\n      readOnlyRootFilesystem: true\n      capabilities:\n        drop: [\"ALL\"]\n",
			NoncompliantExample: "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  containers:\n  - name: test\n    image: test\n",
			RemediationEffort:   15,
		},
		{
			Key: "kubernetes-dangerous-capability", Name: "Dangerous Linux capability added", Language: "Kubernetes", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh, Tags: []string{"kubernetes", "capabilities"}, CWE: []string{"CWE-269"}, OWASP: []string{"A04:2021"}, Detection: rule.DetectionAST,
			Description:         "A highly privileged Linux capability (like SYS_ADMIN, NET_ADMIN, or ALL) is added.",
			Rationale:           "Capabilities like SYS_ADMIN allow almost complete control over the host node. If compromised, an attacker can trivially escape the container.\n\nSource: https://cwe.mitre.org/data/definitions/269.html",
			Remediation:         "Remove the dangerous capability from the `add` list. Refactor the application to not require root-equivalent system access.",
			CompliantExample:    "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  securityContext:\n    runAsNonRoot: true\n    runAsUser: 1000\n    runAsGroup: 1000\n    seccompProfile:\n      type: RuntimeDefault\n  containers:\n  - name: test\n    image: test:1.0@sha256:abc\n    resources:\n      limits:\n        cpu: 100m\n        memory: 128Mi\n    securityContext:\n      allowPrivilegeEscalation: false\n      readOnlyRootFilesystem: true\n      capabilities:\n        drop: [\"ALL\"]\n",
			NoncompliantExample: "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  containers:\n  - name: test\n    image: test\n    securityContext:\n      capabilities:\n        add: [\"SYS_ADMIN\"]\n",
			RemediationEffort:   30,
		},
		{
			Key: "kubernetes-default-namespace", Name: "Workload in the default namespace", Language: "Kubernetes", Type: rule.TypeCodeSmell, Qualities: []rule.Quality{rule.QualityMaintainability}, DefaultSeverity: shared.SeverityLow, Tags: []string{"kubernetes", "namespace"}, CWE: []string{}, OWASP: []string{}, Detection: rule.DetectionAST,
			Description:         "The resource defines its namespace as 'default' or omits it entirely.",
			Rationale:           "Deploying to the default namespace makes managing RBAC, network policies, and resource quotas difficult. Applications should be isolated into dedicated namespaces.\n\nSource: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/",
			Remediation:         "Explicitly declare a meaningful `namespace` in the resource metadata.",
			CompliantExample:    "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\n  namespace: dev\nspec:\n  containers:\n  - name: test\n    image: test:1.0@sha256:abc\n",
			NoncompliantExample: "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  containers:\n  - name: test\n    image: test\n",
			RemediationEffort:   5,
		},
		{
			Key: "kubernetes-host-ipc", Name: "Pod shares the host IPC namespace", Language: "Kubernetes", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh, Tags: []string{"kubernetes", "namespace"}, CWE: []string{"CWE-269"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "The Pod specification sets `hostIPC: true`.",
			Rationale:           "Sharing the host IPC namespace allows the pod to access shared memory and communicate directly with host processes, breaking isolation.\n\nSource: https://kubernetes.io/docs/concepts/security/pod-security-standards/",
			Remediation:         "Remove `hostIPC: true` to enforce strict IPC isolation.",
			CompliantExample:    "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  securityContext:\n    runAsNonRoot: true\n    runAsUser: 1000\n    runAsGroup: 1000\n    seccompProfile:\n      type: RuntimeDefault\n  containers:\n  - name: test\n    image: test:1.0@sha256:abc\n    resources:\n      limits:\n        cpu: 100m\n        memory: 128Mi\n    securityContext:\n      allowPrivilegeEscalation: false\n      readOnlyRootFilesystem: true\n      capabilities:\n        drop: [\"ALL\"]\n",
			NoncompliantExample: "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  hostIPC: true\n  containers:\n  - name: test\n    image: test\n",
			RemediationEffort:   15,
		},
		{
			Key: "kubernetes-host-network", Name: "Pod shares the host network namespace", Language: "Kubernetes", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh, Tags: []string{"kubernetes", "network"}, CWE: []string{"CWE-269"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "The Pod specification sets `hostNetwork: true`.",
			Rationale:           "Host networking allows the pod to listen on node network interfaces and sniff node traffic, circumventing network policies and exposing the node's loopback services.\n\nSource: https://kubernetes.io/docs/concepts/security/pod-security-standards/",
			Remediation:         "Remove `hostNetwork: true`. Use standard Service objects to expose ports.",
			CompliantExample:    "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  securityContext:\n    runAsNonRoot: true\n    runAsUser: 1000\n    runAsGroup: 1000\n    seccompProfile:\n      type: RuntimeDefault\n  containers:\n  - name: test\n    image: test:1.0@sha256:abc\n    resources:\n      limits:\n        cpu: 100m\n        memory: 128Mi\n    securityContext:\n      allowPrivilegeEscalation: false\n      readOnlyRootFilesystem: true\n      capabilities:\n        drop: [\"ALL\"]\n",
			NoncompliantExample: "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  hostNetwork: true\n  containers:\n  - name: test\n    image: test\n",
			RemediationEffort:   15,
		},
		{
			Key: "kubernetes-host-path", Name: "Volume mounts a host path", Language: "Kubernetes", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium, Tags: []string{"kubernetes", "mount"}, CWE: []string{"CWE-250"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "A volume uses the `hostPath` type to mount a directory from the host node.",
			Rationale:           "HostPath mounts give the container direct access to the node's file system. If an attacker writes to critical host paths (like /etc or /var/run), they can completely compromise the node.\n\nSource: https://kubernetes.io/docs/concepts/security/pod-security-standards/",
			Remediation:         "Use managed PersistentVolumes (PVs) or ephemeral EmptyDir volumes instead of HostPath.",
			CompliantExample:    "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  securityContext:\n    runAsNonRoot: true\n    runAsUser: 1000\n    runAsGroup: 1000\n    seccompProfile:\n      type: RuntimeDefault\n  containers:\n  - name: test\n    image: test:1.0@sha256:abc\n    resources:\n      limits:\n        cpu: 100m\n        memory: 128Mi\n    securityContext:\n      allowPrivilegeEscalation: false\n      readOnlyRootFilesystem: true\n      capabilities:\n        drop: [\"ALL\"]\n",
			NoncompliantExample: "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  volumes:\n  - name: v\n    hostPath:\n      path: /etc\n  containers:\n  - name: test\n    image: test\n",
			RemediationEffort:   30,
		},
		{
			Key: "kubernetes-host-pid", Name: "Pod shares the host PID namespace", Language: "Kubernetes", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh, Tags: []string{"kubernetes", "namespace"}, CWE: []string{"CWE-269"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "The Pod specification sets `hostPID: true`.",
			Rationale:           "Sharing the host PID namespace permits the container to view and signal all processes running on the host, nullifying process isolation.\n\nSource: https://kubernetes.io/docs/concepts/security/pod-security-standards/",
			Remediation:         "Remove `hostPID: true` to ensure the pod remains in an isolated PID namespace.",
			CompliantExample:    "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  securityContext:\n    runAsNonRoot: true\n    runAsUser: 1000\n    runAsGroup: 1000\n    seccompProfile:\n      type: RuntimeDefault\n  containers:\n  - name: test\n    image: test:1.0@sha256:abc\n    resources:\n      limits:\n        cpu: 100m\n        memory: 128Mi\n    securityContext:\n      allowPrivilegeEscalation: false\n      readOnlyRootFilesystem: true\n      capabilities:\n        drop: [\"ALL\"]\n",
			NoncompliantExample: "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  hostPID: true\n  containers:\n  - name: test\n    image: test\n",
			RemediationEffort:   15,
		},
		{
			Key: "kubernetes-host-port", Name: "Container binds a host port", Language: "Kubernetes", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium, Tags: []string{"kubernetes", "network"}, CWE: []string{"CWE-284"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "A container's port definition specifies a `hostPort`.",
			Rationale:           "Binding directly to a hostPort bypasses Kubernetes services and network policies, potentially creating port conflicts and exposing the application directly on the node's IP.\n\nSource: https://kubernetes.io/docs/concepts/security/pod-security-standards/",
			Remediation:         "Remove the `hostPort` declaration and rely on a Service of type NodePort or LoadBalancer if external exposure is required.",
			CompliantExample:    "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  securityContext:\n    runAsNonRoot: true\n    runAsUser: 1000\n    runAsGroup: 1000\n    seccompProfile:\n      type: RuntimeDefault\n  containers:\n  - name: test\n    image: test:1.0@sha256:abc\n    resources:\n      limits:\n        cpu: 100m\n        memory: 128Mi\n    securityContext:\n      allowPrivilegeEscalation: false\n      readOnlyRootFilesystem: true\n      capabilities:\n        drop: [\"ALL\"]\n",
			NoncompliantExample: "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  containers:\n  - name: test\n    image: test\n    ports:\n    - containerPort: 80\n      hostPort: 80\n",
			RemediationEffort:   15,
		},
		{
			Key: "kubernetes-image-no-tag", Name: "Container image not version-pinned", Language: "Kubernetes", Type: rule.TypeBug, Qualities: []rule.Quality{rule.QualityReliability}, DefaultSeverity: shared.SeverityLow, Tags: []string{"kubernetes", "reproducibility"}, CWE: []string{}, OWASP: []string{}, Detection: rule.DetectionAST,
			Description:         "A container image does not specify a tag or uses ':latest'.",
			Rationale:           "The 'latest' tag is mutable. Deployments can inadvertently roll out untested breaking changes when a pod restarts and pulls a completely different image version.\n\nSource: https://kubernetes.io/docs/concepts/containers/images/#image-names",
			Remediation:         "Always pin images to a specific version or immutable SHA256 digest in production manifests.",
			CompliantExample:    "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  securityContext:\n    runAsNonRoot: true\n    runAsUser: 1000\n    runAsGroup: 1000\n    seccompProfile:\n      type: RuntimeDefault\n  containers:\n  - name: test\n    image: test:1.0@sha256:abc\n    resources:\n      limits:\n        cpu: 100m\n        memory: 128Mi\n    securityContext:\n      allowPrivilegeEscalation: false\n      readOnlyRootFilesystem: true\n      capabilities:\n        drop: [\"ALL\"]\n",
			NoncompliantExample: "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  containers:\n  - name: test\n    image: test\n",
			RemediationEffort:   5,
		},
		{
			Key: "kubernetes-no-cpu-limit", Name: "No CPU limit", Language: "Kubernetes", Type: rule.TypeBug, Qualities: []rule.Quality{rule.QualityReliability}, DefaultSeverity: shared.SeverityLow, Tags: []string{"kubernetes", "resources"}, CWE: []string{}, OWASP: []string{}, Detection: rule.DetectionAST,
			Description:         "The container spec does not define a CPU limit.",
			Rationale:           "Without CPU limits, a single misbehaving or compromised pod can consume all available CPU on the node, starving other workloads and causing a localized Denial of Service.\n\nSource: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/",
			Remediation:         "Define explicit CPU requests and limits in the `resources` block.",
			CompliantExample:    "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  securityContext:\n    runAsNonRoot: true\n    runAsUser: 1000\n    runAsGroup: 1000\n    seccompProfile:\n      type: RuntimeDefault\n  containers:\n  - name: test\n    image: test:1.0@sha256:abc\n    resources:\n      limits:\n        cpu: 100m\n        memory: 128Mi\n    securityContext:\n      allowPrivilegeEscalation: false\n      readOnlyRootFilesystem: true\n      capabilities:\n        drop: [\"ALL\"]\n",
			NoncompliantExample: "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  containers:\n  - name: test\n    image: test\n",
			RemediationEffort:   15,
		},
		{
			Key: "kubernetes-no-memory-limit", Name: "No memory limit", Language: "Kubernetes", Type: rule.TypeBug, Qualities: []rule.Quality{rule.QualityReliability}, DefaultSeverity: shared.SeverityLow, Tags: []string{"kubernetes", "resources"}, CWE: []string{}, OWASP: []string{}, Detection: rule.DetectionAST,
			Description:         "The container spec does not define a memory limit.",
			Rationale:           "Without memory limits, a memory leak can cause the pod to consume all node memory, triggering the OOMKiller to terminate innocent pods or crash the node entirely.\n\nSource: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/",
			Remediation:         "Define explicit memory requests and limits in the `resources` block.",
			CompliantExample:    "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  securityContext:\n    runAsNonRoot: true\n    runAsUser: 1000\n    runAsGroup: 1000\n    seccompProfile:\n      type: RuntimeDefault\n  containers:\n  - name: test\n    image: test:1.0@sha256:abc\n    resources:\n      limits:\n        cpu: 100m\n        memory: 128Mi\n    securityContext:\n      allowPrivilegeEscalation: false\n      readOnlyRootFilesystem: true\n      capabilities:\n        drop: [\"ALL\"]\n",
			NoncompliantExample: "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  containers:\n  - name: test\n    image: test\n",
			RemediationEffort:   15,
		},
		{
			Key: "kubernetes-no-priv-escalation-disabled", Name: "Privilege escalation not disabled", Language: "Kubernetes", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityLow, Tags: []string{"kubernetes", "privilege"}, CWE: []string{"CWE-250"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "The securityContext does not explicitly set `allowPrivilegeEscalation: false`.",
			Rationale:           "If omitted, Kubernetes defaults to allowing privilege escalation. The Pod Security Standards require explicitly disabling it to prevent setuid binaries from granting root access.\n\nSource: https://kubernetes.io/docs/concepts/security/pod-security-standards/",
			Remediation:         "Add `allowPrivilegeEscalation: false` to the container's securityContext.",
			CompliantExample:    "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  securityContext:\n    runAsNonRoot: true\n    runAsUser: 1000\n    runAsGroup: 1000\n    seccompProfile:\n      type: RuntimeDefault\n  containers:\n  - name: test\n    image: test:1.0@sha256:abc\n    resources:\n      limits:\n        cpu: 100m\n        memory: 128Mi\n    securityContext:\n      allowPrivilegeEscalation: false\n      readOnlyRootFilesystem: true\n      capabilities:\n        drop: [\"ALL\"]\n",
			NoncompliantExample: "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  containers:\n  - name: test\n    image: test\n",
			RemediationEffort:   15,
		},
		{
			Key: "kubernetes-no-read-only-root-fs", Name: "Writable container root filesystem", Language: "Kubernetes", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityLow, Tags: []string{"kubernetes", "filesystem"}, CWE: []string{"CWE-732"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "The container does not set `readOnlyRootFilesystem: true`.",
			Rationale:           "An immutable root filesystem prevents attackers from installing malware, overwriting binaries, or persisting changes within the container during an attack.\n\nSource: https://kubernetes.io/docs/concepts/security/pod-security-standards/",
			Remediation:         "Set `readOnlyRootFilesystem: true` and mount EmptyDir volumes for specific paths (like /tmp) that require write access.",
			CompliantExample:    "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  securityContext:\n    runAsNonRoot: true\n    runAsUser: 1000\n    runAsGroup: 1000\n    seccompProfile:\n      type: RuntimeDefault\n  containers:\n  - name: test\n    image: test:1.0@sha256:abc\n    resources:\n      limits:\n        cpu: 100m\n        memory: 128Mi\n    securityContext:\n      allowPrivilegeEscalation: false\n      readOnlyRootFilesystem: true\n      capabilities:\n        drop: [\"ALL\"]\n",
			NoncompliantExample: "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  containers:\n  - name: test\n    image: test\n",
			RemediationEffort:   30,
		},
		{
			Key: "kubernetes-no-run-as-group", Name: "No explicit runAsGroup", Language: "Kubernetes", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityLow, Tags: []string{"kubernetes", "privilege"}, CWE: []string{"CWE-250"}, OWASP: []string{"A04:2021"}, Detection: rule.DetectionAST,
			Description:         "The securityContext lacks an explicit `runAsGroup` ID.",
			Rationale:           "Enforcing a specific unprivileged group ID ensures the container process runs with known, minimal permissions, defending against group-level privilege escalations.\n\nSource: https://kubernetes.io/docs/concepts/security/pod-security-standards/",
			Remediation:         "Specify an explicit unprivileged group ID using `runAsGroup: 10001`.",
			CompliantExample:    "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  securityContext:\n    runAsNonRoot: true\n    runAsUser: 1000\n    runAsGroup: 1000\n    seccompProfile:\n      type: RuntimeDefault\n  containers:\n  - name: test\n    image: test:1.0@sha256:abc\n    resources:\n      limits:\n        cpu: 100m\n        memory: 128Mi\n    securityContext:\n      allowPrivilegeEscalation: false\n      readOnlyRootFilesystem: true\n      capabilities:\n        drop: [\"ALL\"]\n",
			NoncompliantExample: "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  containers:\n  - name: test\n    image: test\n",
			RemediationEffort:   15,
		},
		{
			Key: "kubernetes-no-run-as-non-root", Name: "Container may run as root", Language: "Kubernetes", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium, Tags: []string{"kubernetes", "privilege"}, CWE: []string{"CWE-250"}, OWASP: []string{"A04:2021"}, Detection: rule.DetectionAST,
			Description:         "The securityContext does not set `runAsNonRoot: true`.",
			Rationale:           "Requiring `runAsNonRoot` instructs the kubelet to refuse starting the container if the image tries to run as root, acting as a final safeguard even if the image metadata changes.\n\nSource: https://kubernetes.io/docs/concepts/security/pod-security-standards/",
			Remediation:         "Set `runAsNonRoot: true` at the pod or container securityContext level.",
			CompliantExample:    "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  securityContext:\n    runAsNonRoot: true\n    runAsUser: 1000\n    runAsGroup: 1000\n    seccompProfile:\n      type: RuntimeDefault\n  containers:\n  - name: test\n    image: test:1.0@sha256:abc\n    resources:\n      limits:\n        cpu: 100m\n        memory: 128Mi\n    securityContext:\n      allowPrivilegeEscalation: false\n      readOnlyRootFilesystem: true\n      capabilities:\n        drop: [\"ALL\"]\n",
			NoncompliantExample: "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  containers:\n  - name: test\n    image: test\n",
			RemediationEffort:   15,
		},
		{
			Key: "kubernetes-no-run-as-user", Name: "No explicit runAsUser", Language: "Kubernetes", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityLow, Tags: []string{"kubernetes", "privilege"}, CWE: []string{"CWE-250"}, OWASP: []string{"A04:2021"}, Detection: rule.DetectionAST,
			Description:         "The securityContext does not explicitly specify a `runAsUser` ID.",
			Rationale:           "Without an explicit unprivileged UID, the container relies entirely on the Dockerfile's USER directive. Explicitly setting it in the manifest guarantees non-root execution.\n\nSource: https://kubernetes.io/docs/concepts/security/pod-security-standards/",
			Remediation:         "Set an explicit, unprivileged numeric UID, such as `runAsUser: 10001`.",
			CompliantExample:    "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  securityContext:\n    runAsNonRoot: true\n    runAsUser: 1000\n    runAsGroup: 1000\n    seccompProfile:\n      type: RuntimeDefault\n  containers:\n  - name: test\n    image: test:1.0@sha256:abc\n    resources:\n      limits:\n        cpu: 100m\n        memory: 128Mi\n    securityContext:\n      allowPrivilegeEscalation: false\n      readOnlyRootFilesystem: true\n      capabilities:\n        drop: [\"ALL\"]\n",
			NoncompliantExample: "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  containers:\n  - name: test\n    image: test\n",
			RemediationEffort:   15,
		},
		{
			Key: "kubernetes-no-seccomp", Name: "No seccomp profile", Language: "Kubernetes", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityLow, Tags: []string{"kubernetes", "seccomp"}, CWE: []string{"CWE-250"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "The pod lacks a seccomp profile definition, defaulting to unconfined behavior on older clusters.",
			Rationale:           "Seccomp limits the syscalls a container can make to the host kernel. Enforcing a profile like RuntimeDefault mitigates numerous kernel zero-day exploits.\n\nSource: https://kubernetes.io/docs/tutorials/security/seccomp/",
			Remediation:         "Specify the `RuntimeDefault` seccomp profile in the Pod's securityContext.",
			CompliantExample:    "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  securityContext:\n    runAsNonRoot: true\n    runAsUser: 1000\n    runAsGroup: 1000\n    seccompProfile:\n      type: RuntimeDefault\n  containers:\n  - name: test\n    image: test:1.0@sha256:abc\n    resources:\n      limits:\n        cpu: 100m\n        memory: 128Mi\n    securityContext:\n      allowPrivilegeEscalation: false\n      readOnlyRootFilesystem: true\n      capabilities:\n        drop: [\"ALL\"]\n",
			NoncompliantExample: "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  containers:\n  - name: test\n    image: test\n",
			RemediationEffort:   15,
		},
		{
			Key: "kubernetes-privileged", Name: "Privileged container", Language: "Kubernetes", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh, Tags: []string{"kubernetes", "privilege"}, CWE: []string{"CWE-269"}, OWASP: []string{"A04:2021"}, Detection: rule.DetectionAST,
			Description:         "The container explicitly sets `privileged: true`.",
			Rationale:           "A privileged container bypasses almost all Kubernetes and Docker security isolations. It can access all host devices and manipulate kernel state, making host takeover trivial.\n\nSource: https://kubernetes.io/docs/concepts/security/pod-security-standards/",
			Remediation:         "Remove `privileged: true`. Identify the specific capability or device needed and request only that minimum privilege.",
			CompliantExample:    "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  securityContext:\n    runAsNonRoot: true\n    runAsUser: 1000\n    runAsGroup: 1000\n    seccompProfile:\n      type: RuntimeDefault\n  containers:\n  - name: test\n    image: test:1.0@sha256:abc\n    resources:\n      limits:\n        cpu: 100m\n        memory: 128Mi\n    securityContext:\n      allowPrivilegeEscalation: false\n      readOnlyRootFilesystem: true\n      capabilities:\n        drop: [\"ALL\"]\n",
			NoncompliantExample: "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  containers:\n  - name: test\n    image: test\n    securityContext:\n      privileged: true\n",
			RemediationEffort:   30,
		},
		{
			Key: "kubernetes-run-as-root", Name: "Container runs as root", Language: "Kubernetes", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium, Tags: []string{"kubernetes", "privilege"}, CWE: []string{"CWE-250"}, OWASP: []string{"A04:2021"}, Detection: rule.DetectionAST,
			Description:         "The securityContext explicitly sets `runAsUser: 0` or `runAsNonRoot: false`.",
			Rationale:           "Running workloads as the root user allows a compromised application to deeply alter the container environment and exploit kernel flaws to break out to the host.\n\nSource: https://kubernetes.io/docs/concepts/security/pod-security-standards/",
			Remediation:         "Change the runAsUser ID to an unprivileged number (e.g., 1000) and set `runAsNonRoot: true`.",
			CompliantExample:    "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  securityContext:\n    runAsNonRoot: true\n    runAsUser: 1000\n    runAsGroup: 1000\n    seccompProfile:\n      type: RuntimeDefault\n  containers:\n  - name: test\n    image: test:1.0@sha256:abc\n    resources:\n      limits:\n        cpu: 100m\n        memory: 128Mi\n    securityContext:\n      allowPrivilegeEscalation: false\n      readOnlyRootFilesystem: true\n      capabilities:\n        drop: [\"ALL\"]\n",
			NoncompliantExample: "apiVersion: v1\nkind: Pod\nmetadata:\n  name: test\nspec:\n  containers:\n  - name: test\n    image: test\n    securityContext:\n      runAsUser: 0\n",
			RemediationEffort:   30,
		},
	}
}

func tfRules() []rule.Rule {
	return []rule.Rule{
		{
			Key: "terraform-cloudwatch-unencrypted", Name: "CloudWatch log group not encrypted with KMS", Language: "Terraform", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityLow, Tags: []string{"terraform", "aws", "encryption"}, CWE: []string{"CWE-311"}, OWASP: []string{"A02:2021"}, Detection: rule.DetectionPattern,
			Description:         "The aws_cloudwatch_log_group lacks a KMS key ID for encryption.",
			Rationale:           "While CloudWatch encrypts logs by default with AWS managed keys, compliance regimes often require using customer-managed KMS keys (CMK) for complete control over cryptographic access.\n\nSource: https://cwe.mitre.org/data/definitions/311.html",
			Remediation:         "Assign a valid ARN to the `kms_key_id` attribute of the log group.",
			CompliantExample:    "resource \"aws_cloudwatch_log_group\" \"app\" {\n  kms_key_id = aws_kms_key.logs.arn\n}",
			NoncompliantExample: "resource \"aws_cloudwatch_log_group\" \"app\" {\n  name = \"app-logs\"\n}",
			RemediationEffort:   15,
		},
		{
			Key: "terraform-db-publicly-accessible", Name: "Database is publicly accessible", Language: "Terraform", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh, Tags: []string{"terraform", "aws", "network"}, CWE: []string{"CWE-284"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionPattern,
			Description:         "An RDS DB instance or cluster sets `publicly_accessible = true`.",
			Rationale:           "Publicly accessible databases are exposed to the entire internet, inviting brute force attacks, exploitation of database engine vulnerabilities, and data theft.\n\nSource: https://cwe.mitre.org/data/definitions/284.html",
			Remediation:         "Set `publicly_accessible = false` and place the database in a private subnet, accessing it via a VPN or bastion host.",
			CompliantExample:    "resource \"aws_db_instance\" \"db\" {\n  publicly_accessible = false\n}",
			NoncompliantExample: "resource \"aws_db_instance\" \"db\" {\n  publicly_accessible = true\n}",
			RemediationEffort:   15,
		},
		{
			Key: "terraform-dynamodb-no-pitr", Name: "DynamoDB point-in-time recovery disabled", Language: "Terraform", Type: rule.TypeBug, Qualities: []rule.Quality{rule.QualityReliability}, DefaultSeverity: shared.SeverityLow, Tags: []string{"terraform", "aws", "backup"}, CWE: []string{}, OWASP: []string{}, Detection: rule.DetectionPattern,
			Description:         "A DynamoDB table does not enable point_in_time_recovery.",
			Rationale:           "Point-in-time recovery protects against accidental writes or deletes. Without it, recovering from a catastrophic application bug or accidental table drop is impossible.\n\nSource: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/PointInTimeRecovery.html",
			Remediation:         "Add a `point_in_time_recovery` block with `enabled = true`.",
			CompliantExample:    "point_in_time_recovery {\n  enabled = true\n}",
			NoncompliantExample: "resource \"aws_dynamodb_table\" \"users\" {\n  name = \"users\"\n}",
			RemediationEffort:   5,
		},
		{
			Key: "terraform-dynamodb-unencrypted", Name: "DynamoDB table not encrypted with a CMK", Language: "Terraform", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium, Tags: []string{"terraform", "aws", "encryption"}, CWE: []string{"CWE-311"}, OWASP: []string{"A02:2021"}, Detection: rule.DetectionPattern,
			Description:         "The DynamoDB table relies on the default AWS owned key instead of a CMK.",
			Rationale:           "Using a Customer Managed Key (CMK) provides audit trails via CloudTrail and allows cryptographic revocation, which the default AWS owned key does not provide.\n\nSource: https://cwe.mitre.org/data/definitions/311.html",
			Remediation:         "Configure `server_side_encryption` with `enabled = true` and specify a `kms_key_arn`.",
			CompliantExample:    "server_side_encryption {\n  enabled     = true\n  kms_key_arn = aws_kms_key.db.arn\n}",
			NoncompliantExample: "resource \"aws_dynamodb_table\" \"users\" {\n  name = \"users\"\n}",
			RemediationEffort:   15,
		},
		{
			Key: "terraform-ebs-unencrypted", Name: "EBS volume not encrypted at rest", Language: "Terraform", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium, Tags: []string{"terraform", "aws", "encryption"}, CWE: []string{"CWE-311"}, OWASP: []string{"A02:2021"}, Detection: rule.DetectionPattern,
			Description:         "An EBS volume disables encryption or omits the encrypted flag.",
			Rationale:           "Unencrypted block storage exposes sensitive operating system and application data at rest. It violates almost all modern security and compliance frameworks.\n\nSource: https://cwe.mitre.org/data/definitions/311.html",
			Remediation:         "Set `encrypted = true` and optionally provide a `kms_key_id`.",
			CompliantExample:    "resource \"aws_ebs_volume\" \"example\" {\n  size = 40\n  encrypted = true\n}",
			NoncompliantExample: "resource \"aws_ebs_volume\" \"example\" {\n  size = 40\n}",
			RemediationEffort:   15,
		},
		{
			Key: "terraform-ecr-mutable-tags", Name: "ECR image tags are mutable", Language: "Terraform", Type: rule.TypeBug, Qualities: []rule.Quality{rule.QualityReliability}, DefaultSeverity: shared.SeverityLow, Tags: []string{"terraform", "aws", "reproducibility"}, CWE: []string{}, OWASP: []string{}, Detection: rule.DetectionPattern,
			Description:         "An ECR repository sets `image_tag_mutability = \"MUTABLE\"`.",
			Rationale:           "Mutable image tags allow an attacker or developer to overwrite an existing tag (like 'v1.0') with a new image, breaking reproducibility and rollback mechanisms.\n\nSource: https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-tag-mutability.html",
			Remediation:         "Set `image_tag_mutability = \"IMMUTABLE\"`.",
			CompliantExample:    "resource \"aws_ecr_repository\" \"app\" {\n  image_tag_mutability = \"IMMUTABLE\"\n}",
			NoncompliantExample: "resource \"aws_ecr_repository\" \"app\" {\n  image_tag_mutability = \"MUTABLE\"\n}",
			RemediationEffort:   5,
		},
		{
			Key: "terraform-ecr-no-cmk", Name: "ECR repository not encrypted with a customer-managed key", Language: "Terraform", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityLow, Tags: []string{"terraform", "aws", "encryption"}, CWE: []string{"CWE-311"}, OWASP: []string{"A02:2021"}, Detection: rule.DetectionPattern,
			Description:         "An ECR repository uses AES256 encryption rather than a KMS key.",
			Rationale:           "Encrypting container images with a Customer Managed Key (CMK) provides fine-grained access control over who can decrypt and pull the image, defending against registry exposure.\n\nSource: https://cwe.mitre.org/data/definitions/311.html",
			Remediation:         "Configure an `encryption_configuration` block with `encryption_type = \"KMS\"`.",
			CompliantExample:    "encryption_configuration {\n  encryption_type = \"KMS\"\n  kms_key         = aws_kms_key.ecr.arn\n}",
			NoncompliantExample: "resource \"aws_ecr_repository\" \"app\" {\n  name = \"app\"\n}",
			RemediationEffort:   15,
		},
		{
			Key: "terraform-encryption-disabled", Name: "Encryption explicitly disabled", Language: "Terraform", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh, Tags: []string{"terraform", "encryption"}, CWE: []string{"CWE-311"}, OWASP: []string{"A02:2021"}, Detection: rule.DetectionPattern,
			Description:         "A storage or queue resource explicitly sets `encrypted = false`.",
			Rationale:           "Explicitly disabling encryption exposes data at rest. Always encrypt data at rest to mitigate physical compromise and unauthorized snapshot sharing.\n\nSource: https://cwe.mitre.org/data/definitions/311.html",
			Remediation:         "Remove the `encrypted = false` declaration or set it to `true`.",
			CompliantExample:    "encrypted = true",
			NoncompliantExample: "encrypted = false",
			RemediationEffort:   15,
		},
		{
			Key: "terraform-iam-wildcard", Name: "IAM policy grants a wildcard action", Language: "Terraform", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium, Tags: []string{"terraform", "aws", "iam"}, CWE: []string{"CWE-732"}, OWASP: []string{"A01:2021"}, Detection: rule.DetectionPattern,
			Description:         "An IAM policy document grants a wildcard (*) action or resource.",
			Rationale:           "Wildcard IAM permissions violate least privilege, granting excessive access that allows an attacker to pivot, escalate privileges, and compromise the entire AWS account.\n\nSource: https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#grant-least-privilege",
			Remediation:         "Replace wildcards with explicitly enumerated, necessary actions and specific ARNs.",
			CompliantExample:    "actions = [\"s3:GetObject\"]\nresources = [\"arn:aws:s3:::my-bucket/*\"]",
			NoncompliantExample: "actions = [\"*\"]\nresources = [\"*\"]",
			RemediationEffort:   30,
		},
		{
			Key: "terraform-imdsv2-not-required", Name: "IMDSv2 not enforced", Language: "Terraform", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium, Tags: []string{"terraform", "aws", "imds"}, CWE: []string{"CWE-918"}, OWASP: []string{"A01:2021"}, Detection: rule.DetectionPattern,
			Description:         "An EC2 instance or launch template does not enforce IMDSv2 via `http_tokens = \"required\"`.",
			Rationale:           "IMDSv1 is vulnerable to SSRF attacks, allowing attackers to easily extract IAM credentials from the instance metadata service. IMDSv2 requires a session token, heavily mitigating this risk.\n\nSource: https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/",
			Remediation:         "Configure the `metadata_options` block with `http_tokens = \"required\"`.",
			CompliantExample:    "resource \"aws_instance\" \"web\" {\n  ami = \"ami-123456\"\n  instance_type = \"t2.micro\"\n  metadata_options {\n    http_tokens = \"required\"\n  }\n}",
			NoncompliantExample: "resource \"aws_instance\" \"web\" {\n  ami = \"ami-123456\"\n  instance_type = \"t2.micro\"\n}",
			RemediationEffort:   15,
		},
		{
			Key: "terraform-open-cidr", Name: "Network rule open to the whole internet", Language: "Terraform", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh, Tags: []string{"terraform", "aws", "network"}, CWE: []string{"CWE-284"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionPattern,
			Description:         "An ingress security group rule allows traffic from 0.0.0.0/0 or ::/0.",
			Rationale:           "Allowing inbound traffic from any IP address exposes the application to global scanning, brute force attacks, and zero-day exploits.\n\nSource: https://cwe.mitre.org/data/definitions/284.html",
			Remediation:         "Restrict the `cidr_blocks` to an internal VPC range, a VPN IP, or a corporate network CIDR.",
			CompliantExample:    "cidr_blocks = [\"10.0.0.0/8\"]",
			NoncompliantExample: "cidr_blocks = [\"0.0.0.0/0\"]",
			RemediationEffort:   15,
		},
		{
			Key: "terraform-open-egress", Name: "Security group egress open to the whole internet", Language: "Terraform", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium, Tags: []string{"terraform", "aws", "network"}, CWE: []string{"CWE-284"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionPattern,
			Description:         "An egress security group rule allows outbound traffic to 0.0.0.0/0.",
			Rationale:           "Unrestricted egress allows compromised instances to easily download malware, join botnets, or exfiltrate sensitive data to arbitrary external IP addresses.\n\nSource: https://cwe.mitre.org/data/definitions/284.html",
			Remediation:         "Scope down the `cidr_blocks` in the egress rule to the specific IPs or internal ranges the service must communicate with.",
			CompliantExample:    "egress {\n  cidr_blocks = [\"10.0.0.0/16\"]\n}",
			NoncompliantExample: "egress {\n  cidr_blocks = [\"0.0.0.0/0\"]\n}",
			RemediationEffort:   30,
		},
		{
			Key: "terraform-plaintext-secret", Name: "Secret hardcoded in Terraform", Language: "Terraform", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh, Tags: []string{"terraform", "credentials"}, CWE: []string{"CWE-798"}, OWASP: []string{"A07:2021"}, Detection: rule.DetectionPattern,
			Description:         "A plaintext password or secret key is hardcoded into the Terraform configuration.",
			Rationale:           "Embedding secrets in Terraform manifests permanently leaks them to the version control system and the Terraform state file, compromising the corresponding systems.\n\nSource: https://cwe.mitre.org/data/definitions/798.html",
			Remediation:         "Inject secrets dynamically using environment variables, Terraform variables, or a data source pulling from AWS Secrets Manager.",
			CompliantExample:    "password = var.db_password",
			NoncompliantExample: "password = \"example-password\"",
			RemediationEffort:   15,
		},
		{
			Key: "terraform-public-access-block-disabled", Name: "Public-access block disabled", Language: "Terraform", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium, Tags: []string{"terraform", "aws", "s3"}, CWE: []string{"CWE-732"}, OWASP: []string{"A01:2021"}, Detection: rule.DetectionPattern,
			Description:         "An S3 bucket does not configure `aws_s3_bucket_public_access_block` to true.",
			Rationale:           "The Public Access Block acts as a failsafe against accidental public ACLs or bucket policies. Without it, a single misconfigured policy can instantly expose the bucket to the internet.\n\nSource: https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html",
			Remediation:         "Create an `aws_s3_bucket_public_access_block` resource associated with the bucket, setting all four blocking options to true.",
			CompliantExample:    "resource \"aws_s3_bucket_public_access_block\" \"example\" {\n  bucket = \"x\"\n  block_public_acls = true\n  block_public_policy = true\n  ignore_public_acls = true\n  restrict_public_buckets = true\n}",
			NoncompliantExample: "resource \"aws_s3_bucket_public_access_block\" \"example\" {\n  bucket = \"x\"\n  block_public_acls = false\n  block_public_policy = false\n  ignore_public_acls = false\n  restrict_public_buckets = false\n}",
			RemediationEffort:   15,
		},
		{
			Key: "terraform-public-bucket-acl", Name: "Object storage granted a public ACL", Language: "Terraform", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh, Tags: []string{"terraform", "aws", "s3"}, CWE: []string{"CWE-732"}, OWASP: []string{"A01:2021"}, Detection: rule.DetectionPattern,
			Description:         "An S3 bucket sets `acl = \"public-read\"` or `\"public-read-write\"`.",
			Rationale:           "Public ACLs grant unauthenticated internet users the ability to read or modify bucket objects, resulting in catastrophic data leakage.\n\nSource: https://cwe.mitre.org/data/definitions/732.html",
			Remediation:         "Remove the public ACL declaration. Use IAM and explicit Bucket Policies for granular access control.",
			CompliantExample:    "acl = \"private\"",
			NoncompliantExample: "acl = \"public-read\"",
			RemediationEffort:   15,
		},
		{
			Key: "terraform-rds-deletion-protection-disabled", Name: "RDS deletion protection is not enabled", Language: "Terraform", Type: rule.TypeBug, Qualities: []rule.Quality{rule.QualityReliability}, DefaultSeverity: shared.SeverityLow, Tags: []string{"terraform", "aws", "rds"}, CWE: []string{}, OWASP: []string{}, Detection: rule.DetectionPattern,
			Description:         "An RDS instance explicitly sets `deletion_protection = false` or omits it.",
			Rationale:           "Without deletion protection, a single accidental or unauthorized `terraform destroy` or API call will instantly delete the database and all its data.\n\nSource: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_DeleteInstance.html",
			Remediation:         "Set `deletion_protection = true` on production database instances.",
			CompliantExample:    "resource \"aws_db_instance\" \"default\" {\n  allocated_storage = 10\n  deletion_protection = true\n}",
			NoncompliantExample: "resource \"aws_db_instance\" \"default\" {\n  allocated_storage = 10\n}",
			RemediationEffort:   5,
		},
		{
			Key: "terraform-s3-no-logging", Name: "S3 bucket access logging disabled", Language: "Terraform", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityLow, Tags: []string{"terraform", "aws", "s3"}, CWE: []string{"CWE-778"}, OWASP: []string{"A09:2021"}, Detection: rule.DetectionPattern,
			Description:         "An S3 bucket does not configure an `aws_s3_bucket_logging` resource.",
			Rationale:           "Access logging is critical for auditing data access and detecting unauthorized data exfiltration or bucket enumeration during a security incident.\n\nSource: https://cwe.mitre.org/data/definitions/778.html",
			Remediation:         "Create an `aws_s3_bucket_logging` resource pointing to a centralized logging bucket.",
			CompliantExample:    "resource \"aws_s3_bucket_logging\" \"app\" {\n  bucket = aws_s3_bucket.app.id\n  target_bucket = aws_s3_bucket.logs.id\n  target_prefix = \"log/\"\n}",
			NoncompliantExample: "resource \"aws_s3_bucket\" \"app\" {}",
			RemediationEffort:   15,
		},
		{
			Key: "terraform-s3-no-versioning", Name: "S3 bucket versioning not enabled", Language: "Terraform", Type: rule.TypeBug, Qualities: []rule.Quality{rule.QualityReliability}, DefaultSeverity: shared.SeverityLow, Tags: []string{"terraform", "aws", "s3"}, CWE: []string{}, OWASP: []string{}, Detection: rule.DetectionPattern,
			Description:         "An S3 bucket does not configure versioning.",
			Rationale:           "Versioning prevents accidental data loss from object overwrites or deletions by retaining older iterations of an object, providing a trivial rollback mechanism.\n\nSource: https://docs.aws.amazon.com/AmazonS3/latest/userguide/Versioning.html",
			Remediation:         "Create an `aws_s3_bucket_versioning` resource and set status to 'Enabled'.",
			CompliantExample:    "resource \"aws_s3_bucket_versioning\" \"app\" {\n  versioning_configuration {\n    status = \"Enabled\"\n  }\n}",
			NoncompliantExample: "resource \"aws_s3_bucket\" \"app\" {}",
			RemediationEffort:   5,
		},
		{
			Key: "terraform-sns-unencrypted", Name: "SNS topic not encrypted", Language: "Terraform", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium, Tags: []string{"terraform", "aws", "sns"}, CWE: []string{"CWE-311"}, OWASP: []string{"A02:2021"}, Detection: rule.DetectionPattern,
			Description:         "An SNS topic omits the `kms_master_key_id` attribute.",
			Rationale:           "Messages published to an unencrypted SNS topic may contain sensitive application data or PII, which will be stored at rest unencrypted within the SNS infrastructure.\n\nSource: https://cwe.mitre.org/data/definitions/311.html",
			Remediation:         "Specify a `kms_master_key_id` to encrypt the SNS topic messages at rest.",
			CompliantExample:    "resource \"aws_sns_topic\" \"alerts\" {\n  kms_master_key_id = aws_kms_key.sns.id\n}",
			NoncompliantExample: "resource \"aws_sns_topic\" \"alerts\" {\n  name = \"alerts\"\n}",
			RemediationEffort:   15,
		},
	}
}
