package rulecatalog

import (
	"github.com/KKloudTarus/synapse-ce/internal/domain/rule"
	"github.com/KKloudTarus/synapse-ce/internal/domain/shared"
)

func reliabilityRules() []rule.Rule {
	return []rule.Rule{
		{
			Key:                 "reliability-empty-catch",
			Name:                "Empty exception handler swallows errors",
			Language:            "General",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"reliability", "error-handling"},
			CWE:                 []string{"CWE-390"},
			OWASP:               []string{},
			Description:         "Detects an empty exception or error-handling block that catches an error but takes no action.",
			Rationale:           "Swallowing exceptions silently hides unexpected application states and failures, severely complicating debugging and potentially leaving the system in an inconsistent state.\n\nSource: https://cwe.mitre.org/data/definitions/390.html",
			Remediation:         "Handle the exception appropriately by logging the error, rethrowing it, or taking a corrective action. If the exception is safely ignored, document the reasoning with a comment.",
			CompliantExample:    "try { doRiskyOperation(); } catch (Exception e) { logger.error(\"failed\", e); }",
			NoncompliantExample: "try { doRiskyOperation(); } catch (Exception e) {}",
			RemediationEffort:   5,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "reliability-self-assignment",
			Name:                "Self-assignment has no effect",
			Language:            "General",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"reliability", "logic"},
			CWE:                 []string{"CWE-1164"},
			OWASP:               []string{},
			Description:         "Detects when a variable or property is assigned to itself.",
			Rationale:           "Self-assignment is functionally useless and almost always indicates a typographical error where a different variable or field was intended to be used on one side of the assignment.\n\nSource: https://cwe.mitre.org/data/definitions/1164.html",
			Remediation:         "Correct the assignment to use the intended variables, or remove the assignment if it is genuinely unnecessary.",
			CompliantExample:    "this.value = newValue;",
			NoncompliantExample: "this.value = this.value;",
			RemediationEffort:   5,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "reliability-self-comparison",
			Name:                "Comparison of a value to itself",
			Language:            "General",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"reliability", "logic"},
			CWE:                 []string{"CWE-571"},
			OWASP:               []string{},
			Description:         "Detects when a variable or expression is compared against itself for equality or inequality.",
			Rationale:           "Self-comparison evaluates to a constant value and almost always indicates a logic error or typo, often resulting from copy-pasting code.\n\nSource: https://cwe.mitre.org/data/definitions/571.html",
			Remediation:         "Correct the condition to compare the intended variables or remove the redundant check.",
			CompliantExample:    "if (a == b) { return true; }",
			NoncompliantExample: "if (a == a) { return true; }",
			RemediationEffort:   5,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "reliability-unreachable-code",
			Name:                "Unreachable code block",
			Language:            "General",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"reliability", "logic", "dead-code"},
			CWE:                 []string{"CWE-561"},
			OWASP:               []string{},
			Description:         "Detects code that can never be executed because there is no valid control-flow path to it.",
			Rationale:           "Unreachable code is dead code that clutters the application. It often reveals a logic error in the preceding control flow, such as an unintended early return or an incorrectly formed condition.\n\nSource: https://cwe.mitre.org/data/definitions/561.html",
			Remediation:         "Remove the unreachable code or fix the preceding control flow logic if the code was intended to be executed.",
			CompliantExample:    "func process() {\n\tdoWork()\n\treturn\n}",
			NoncompliantExample: "func process() {\n\treturn\n\tdoWork()\n}",
			RemediationEffort:   15,
			Detection:           rule.DetectionAST,
		},
		{
			Key:                 "reliability-constant-condition",
			Name:                "Condition is always constant",
			Language:            "General",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"reliability", "logic"},
			CWE:                 []string{"CWE-570"},
			OWASP:               []string{},
			Description:         "Detects a boolean condition that always evaluates to true or always evaluates to false.",
			Rationale:           "A constant condition usually indicates a flawed logical expression or an incorrect assumption about program state, resulting in dead code branches or infinite loops.\n\nSource: https://cwe.mitre.org/data/definitions/570.html",
			Remediation:         "Correct the logical expression so that it correctly captures the intended dynamic condition.",
			CompliantExample:    "if (count > 0) {\n\tprocessItems();\n}",
			NoncompliantExample: "if (false) {\n\tprocessItems();\n}",
			RemediationEffort:   15,
			Detection:           rule.DetectionAST,
		},
	}
}
