package rulecatalog

import (
	"github.com/KKloudTarus/synapse-ce/internal/domain/rule"
	"github.com/KKloudTarus/synapse-ce/internal/domain/shared"
)

func secretRules() []rule.Rule {
	return []rule.Rule{
		{
			Key:                 "aws-access-key-id",
			Name:                "AWS access key ID",
			Language:            "Secrets",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"credentials", "aws"},
			CWE:                 []string{"CWE-798"},
			OWASP:               []string{"A07:2021"},
			Description:         "Detects hardcoded AWS access key IDs.",
			Rationale:           "Hardcoded AWS credentials can be extracted from source code and used by an attacker to impersonate the associated IAM principal, potentially leading to a complete cloud environment compromise.\n\nSource: https://cwe.mitre.org/data/definitions/798.html",
			Remediation:         "Remove the hardcoded key. Use IAM roles, environment variables, or a secure secrets manager to provide AWS credentials at runtime.",
			CompliantExample:    "sess, err := session.NewSession()",
			NoncompliantExample: "awsAccessKeyId := \"AKIAIOSFODNN7EXAMPLE\"",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "github-token",
			Name:                "GitHub token",
			Language:            "Secrets",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"credentials", "github"},
			CWE:                 []string{"CWE-798"},
			OWASP:               []string{"A07:2021"},
			Description:         "Detects hardcoded GitHub personal access tokens or OAuth tokens.",
			Rationale:           "Leaked GitHub tokens grant an attacker access to repositories, packages, and potentially administrative controls over the organization, leading to source code theft or supply chain attacks.\n\nSource: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository",
			Remediation:         "Revoke the leaked token immediately and remove it from the code. Use GitHub Apps or environment-injected secrets instead.",
			CompliantExample:    "token := os.Getenv(\"GITHUB_TOKEN\")",
			NoncompliantExample: "token := \"ghp_16C7e42k292cMGXQ7z18GgXv1BwG4V1EXAMPLE\"",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "gitlab-pat",
			Name:                "GitLab personal access token",
			Language:            "Secrets",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"credentials", "gitlab"},
			CWE:                 []string{"CWE-798"},
			OWASP:               []string{"A07:2021"},
			Description:         "Detects hardcoded GitLab personal access tokens.",
			Rationale:           "Leaked GitLab tokens can be used to bypass authentication and gain unauthorized access to repositories, CI/CD pipelines, and infrastructure.\n\nSource: https://docs.gitlab.com/ee/security/token_overview.html",
			Remediation:         "Revoke the token and remove it from the source tree. Supply credentials using CI/CD variables or external secret stores.",
			CompliantExample:    "token := os.Getenv(\"GITLAB_TOKEN\")",
			NoncompliantExample: "pat := \"glpat-EXAMPLETOKEN1234567890\"",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "slack-token",
			Name:                "Slack token",
			Language:            "Secrets",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"credentials", "slack"},
			CWE:                 []string{"CWE-798"},
			OWASP:               []string{"A07:2021"},
			Description:         "Detects hardcoded Slack API tokens.",
			Rationale:           "Leaked Slack tokens can expose internal communications, private channels, and allow attackers to masquerade as employees or bots to launch social engineering attacks.\n\nSource: https://api.slack.com/authentication/best-practices",
			Remediation:         "Revoke the token in the Slack app console and remove it from the code. Inject the token at runtime using an environment variable.",
			CompliantExample:    "api := slack.New(os.Getenv(\"SLACK_BOT_TOKEN\"))",
			NoncompliantExample: "api := slack.New(\"xoxb-EXAMPLE-TOKEN-DO-NOT-USE-123\")",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "google-api-key",
			Name:                "Google API key",
			Language:            "Secrets",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"credentials", "google"},
			CWE:                 []string{"CWE-798"},
			OWASP:               []string{"A07:2021"},
			Description:         "Detects hardcoded Google Cloud or Maps API keys.",
			Rationale:           "Leaked Google API keys can be abused by third parties to consume quota, resulting in significant financial charges or denial of service.\n\nSource: https://cloud.google.com/docs/authentication/api-keys#securing_an_api_key",
			Remediation:         "Restrict the key's usage in the Google Cloud Console (e.g., by referring URL or IP) and move the raw key to a secure configuration store.",
			CompliantExample:    "apiKey := config.GoogleAPIKey",
			NoncompliantExample: "apiKey := \"<REDACTED_GOOGLE_API_KEY>\"",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "private-key",
			Name:                "Private key block",
			Language:            "Secrets",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityCritical,
			Tags:                []string{"credentials", "cryptography"},
			CWE:                 []string{"CWE-321"},
			OWASP:               []string{"A07:2021"},
			Description:         "Detects hardcoded cryptographic private keys (e.g., RSA, EC, DSA, OpenSSH).",
			Rationale:           "Embedding private keys in source code compromises the fundamental security of any cryptographic protocol relying on them, allowing attackers to decrypt data, forge signatures, or authenticate as the key owner.\n\nSource: https://cwe.mitre.org/data/definitions/321.html",
			Remediation:         "Generate a new key pair. Remove the compromised private key from the source tree and load the new key securely from a keystore or HSM at runtime.",
			CompliantExample:    "keyBytes, err := ioutil.ReadFile(\"/etc/secrets/tls.key\")",
			NoncompliantExample: "var key = `-----BEGIN PRIVATE KEY-----\nMIIEvAIB... (key data) ...\n-----END PRIVATE KEY-----`",
			RemediationEffort:   30,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "jwt",
			Name:                "JSON Web Token",
			Language:            "Secrets",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"credentials", "jwt"},
			CWE:                 []string{"CWE-798"},
			OWASP:               []string{"A07:2021"},
			Description:         "Detects hardcoded JSON Web Tokens (JWTs).",
			Rationale:           "Hardcoded JWTs embedded in code or configuration can be extracted to impersonate users or bypass authorization. Even if expired, they can reveal sensitive claims about the application's internal structure.\n\nSource: https://cheatsheetseries.owasp.org/cheatsheets/JSON_Web_Token_for_Java_Cheat_Sheet.html",
			Remediation:         "Remove the JWT. Design the application to obtain tokens dynamically through a secure authentication flow.",
			CompliantExample:    "req.Header.Set(\"Authorization\", \"Bearer \"+session.Token)",
			NoncompliantExample: "const testToken = \"eyJhbGciOiJIUzI1NiIsInR5cCI.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZS.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c\"",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "generic-secret",
			Name:                "Hardcoded secret",
			Language:            "Secrets",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"credentials"},
			CWE:                 []string{"CWE-798"},
			OWASP:               []string{"A07:2021"},
			Description:         "Detects high-entropy strings assigned to variables that appear to hold secrets, passwords, or API keys.",
			Rationale:           "Storing generic secrets in plaintext exposes them to anyone with read access to the repository, leading to unauthorized access to downstream systems.\n\nSource: https://cwe.mitre.org/data/definitions/798.html",
			Remediation:         "Remove the plaintext secret. Store it in a secure vault or inject it via environment variables.",
			CompliantExample:    "dbPassword := os.Getenv(\"DB_PASSWORD\")",
			NoncompliantExample: "dbPassword := \"V3ryC0mpl3xP@ssw0rd!9876\"",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
	}
}
