package rulecatalog

import (
	"github.com/KKloudTarus/synapse-ce/internal/domain/rule"
	"github.com/KKloudTarus/synapse-ce/internal/domain/shared"
)

func xmlRules() []rule.Rule {
	return []rule.Rule{
		{
			Key:                 "xml:not-well-formed",
			Name:                "XML document is not well formed",
			Language:            "XML",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"xml", "well-formedness"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects XML files that cannot be parsed as a single well-formed document.",
			Rationale:           "XML processors are required to reject documents that violate well-formedness constraints, so malformed configuration can fail at load time or be ignored by downstream tooling.\n\nSource: https://www.w3.org/TR/xml/",
			Remediation:         "Fix the XML structure so tags are properly nested, each document has one root element, and markup syntax is valid.",
			CompliantExample:    "<service><name>api</name></service>",
			NoncompliantExample: "<service name=api></service>",
			RemediationEffort:   5,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:duplicate-attribute",
			Name:                "Duplicate XML attribute",
			Language:            "XML",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityLow,
			Tags:                []string{"xml", "well-formedness", "attributes"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects an XML start tag that repeats the same attribute name.",
			Rationale:           "XML well-formedness requires each attribute name to appear at most once on a single start tag; duplicates make the element invalid and can create ambiguous configuration values.\n\nSource: https://www.w3.org/TR/xml/",
			Remediation:         "Keep a single value for the attribute and remove the duplicate, or split distinct meanings into differently named attributes.",
			CompliantExample:    "<service name=\"api\" role=\"worker\" />",
			NoncompliantExample: "<service name=\"api\" name=\"worker\" />",
			RemediationEffort:   5,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:external-entity",
			Name:                "External general entity declaration",
			Language:            "XML",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"xml", "xxe", "injection", "security"},
			CWE:                 []string{"CWE-611"},
			OWASP:               []string{"A05:2021"},
			Description:         "Detects general external entity declarations in XML DTD markup.",
			Rationale:           "External general entities allow XML parsers to fetch local files or external resources, opening vectors for XML External Entity (XXE) data disclosure attacks.\n\nSource: https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html",
			Remediation:         "Disable DTD processing or external entity resolution in XML parser configuration, or replace external entity declarations with inline static values.",
			CompliantExample:    "<!DOCTYPE config [\n  <!ENTITY appName \"Synapse\">\n]>\n<config>&appName;</config>",
			NoncompliantExample: "<!DOCTYPE config [\n  <!ENTITY xxe SYSTEM \"file:///etc/passwd\">\n]>\n<config>&xxe;</config>",
			RemediationEffort:   15,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:external-dtd",
			Name:                "External DOCTYPE declaration",
			Language:            "XML",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"xml", "xxe", "dtd", "security"},
			CWE:                 []string{"CWE-611"},
			OWASP:               []string{"A05:2021"},
			Description:         "Detects DOCTYPE declarations that reference an external DTD subset via SYSTEM or PUBLIC identifiers.",
			Rationale:           "External DTD subsets enable remote DTD loading, which can lead to Server-Side Request Forgery (SSRF) or out-of-band XXE exploitation.\n\nSource: https://cwe.mitre.org/data/definitions/611.html",
			Remediation:         "Remove external DTD references or configure the XML parser to disallow external DTD loading completely.",
			CompliantExample:    "<!DOCTYPE root [\n  <!ELEMENT root (#PCDATA)>\n]>\n<root>content</root>",
			NoncompliantExample: "<!DOCTYPE root SYSTEM \"https://example.invalid/external.dtd\">\n<root>content</root>",
			RemediationEffort:   15,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:external-parameter-entity",
			Name:                "External parameter entity declaration",
			Language:            "XML",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"xml", "xxe", "parameter-entity", "security"},
			CWE:                 []string{"CWE-611"},
			OWASP:               []string{"A05:2021"},
			Description:         "Detects external parameter entity declarations in XML DTD subsets.",
			Rationale:           "External parameter entities can be used to construct blind or out-of-band XXE exfiltration payloads during DTD evaluation.\n\nSource: https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html",
			Remediation:         "Disable parameter entity resolution and external DTD processing in your XML parser settings.",
			CompliantExample:    "<!DOCTYPE data [\n  <!ENTITY % local \"INCLUDE\">\n]>\n<data>test</data>",
			NoncompliantExample: "<!DOCTYPE data [\n  <!ENTITY % remote SYSTEM \"https://example.invalid/remote.dtd\">\n]>\n<data>test</data>",
			RemediationEffort:   15,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:xinclude",
			Name:                "XInclude element in XML document",
			Language:            "XML",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"xml", "xinclude", "injection", "security"},
			CWE:                 []string{"CWE-611"},
			OWASP:               []string{"A05:2021"},
			Description:         "Detects XInclude elements in XML documents.",
			Rationale:           "XInclude processing enables embedding external documents or local file content into XML documents at parse time, creating file inclusion risks.\n\nSource: https://www.w3.org/TR/xinclude/",
			Remediation:         "Disable XInclude processing in XML parser configuration if external document inclusion is not strictly required.",
			CompliantExample:    "<document xmlns=\"http://example.org/ns\">\n  <content>Hello World</content>\n</document>",
			NoncompliantExample: "<document xmlns:xi=\"http://www.w3.org/2001/XInclude\">\n  <xi:include href=\"file:///etc/passwd\" />\n</document>",
			RemediationEffort:   15,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:entity-expansion",
			Name:                "Dangerous XML entity expansion structure",
			Language:            "XML",
			Type:                rule.TypeSecurityHotspot,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"xml", "dos", "entity-expansion", "security"},
			CWE:                 []string{"CWE-776"},
			OWASP:               []string{"A05:2021"},
			Description:         "Detects dangerous or highly nested internal entity expansion structures.",
			Rationale:           "Excessive entity reference multiplication (Billion Laughs attack) can cause exponential memory consumption and parser Denial of Service.\n\nSource: https://cwe.mitre.org/data/definitions/776.html",
			Remediation:         "Limit or disable internal entity expansion in XML parser options and set entity expansion depth limits.",
			CompliantExample:    "<!DOCTYPE msg [\n  <!ENTITY greeting \"Hello\">\n]>\n<msg>&greeting;</msg>",
			NoncompliantExample: "<!DOCTYPE msg [\n  <!ENTITY a \"lol\">\n  <!ENTITY b \"&a;&a;&a;&a;&a;&a;&a;&a;&a;&a;\">\n  <!ENTITY c \"&b;&b;&b;&b;&b;&b;&b;&b;&b;&b;\">\n  <!ENTITY d \"&c;&c;&c;&c;&c;&c;&c;&c;&c;&c;\">\n]>\n<msg>&d;</msg>",
			RemediationEffort:   15,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:doctype-present",
			Name:                "XML DOCTYPE declaration present",
			Language:            "XML",
			Type:                rule.TypeSecurityHotspot,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"xml", "doctype", "security"},
			CWE:                 []string{"CWE-611"},
			OWASP:               []string{"A05:2021"},
			Description:         "Detects the presence of a DOCTYPE declaration in XML documents.",
			Rationale:           "DOCTYPE declarations enable DTD parsing, which must be reviewed to ensure external entities and DTD loading are hardened against XXE.\n\nSource: https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html",
			Remediation:         "If DTD features are unneeded, remove the DOCTYPE declaration or explicitly disable DTD processing in your parser configuration.",
			CompliantExample:    "<catalog>\n  <item id=\"1\">Book</item>\n</catalog>",
			NoncompliantExample: "<!DOCTYPE catalog [\n  <!ELEMENT catalog (item*)>\n]>\n<catalog/>",
			RemediationEffort:   5,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:external-schema-location",
			Name:                "External XML schema location reference",
			Language:            "XML",
			Type:                rule.TypeSecurityHotspot,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"xml", "schema", "ssrf", "security"},
			CWE:                 []string{"CWE-611", "CWE-918"},
			OWASP:               []string{"A05:2021", "A10:2021"},
			Description:         "Detects external schema locations in xsi:schemaLocation or xsi:noNamespaceSchemaLocation attributes.",
			Rationale:           "Parsing XML with external schema locations can trigger automatic HTTP/FTP connections to remote servers, enabling SSRF or schema poisoning.\n\nSource: https://cwe.mitre.org/data/definitions/918.html",
			Remediation:         "Use local relative schema paths or pre-load XML schemas into an offline XML schema cache.",
			CompliantExample:    "<config xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n        xsi:noNamespaceSchemaLocation=\"schemas/config.xsd\">\n</config>",
			NoncompliantExample: "<config xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n        xsi:noNamespaceSchemaLocation=\"https://example.invalid/schemas/config.xsd\">\n</config>",
			RemediationEffort:   5,
			Detection:           rule.DetectionParse,
		},
		{
			Key:              "xml:hardcoded-secret",
			Name:             "Hardcoded secret in XML configuration",
			Language:         "XML",
			Type:             rule.TypeSecurityHotspot,
			Qualities:        []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:  shared.SeverityMedium,
			Tags:             []string{"xml", "secrets", "credentials", "security"},
			CWE:              []string{"CWE-798"},
			OWASP:            []string{"A07:2021"},
			Description:      "Detects literal passwords, private keys, or API tokens in XML attributes or element text.",
			Rationale:        "Hardcoded credentials in source control or configuration files expose sensitive access tokens to unauthorized readers.\n\nSource: https://cwe.mitre.org/data/definitions/798.html",
			Remediation:      "Store credentials in environment variables or a secret vault and reference them via runtime interpolation (e.g., ${DB_PASSWORD}).",
			CompliantExample: "<database>\n  <password>${DB_PASSWORD}</password>\n</database>",
			NoncompliantExample: "<database>\n  <password>literal-" +
				"credential-value</password>\n</database>",
			RemediationEffort: 15,
			Detection:         rule.DetectionParse,
		},
		{
			Key:                 "xml:mismatched-tag",
			Name:                "Mismatched XML end tag",
			Language:            "XML",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"xml", "well-formedness", "syntax"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects an XML end tag that does not match the currently open element.",
			Rationale:           "W3C XML well-formedness constraints require every start tag to have a strictly matching end tag. Mismatched tags prevent parsing and indicate structural corruption.\n\nSource: https://www.w3.org/TR/xml/#dt-etag",
			Remediation:         "Ensure the end tag exactly matches the name of the corresponding start tag, preserving case.",
			CompliantExample:    "<root><item></item></root>",
			NoncompliantExample: "<root><item></other></root>",
			RemediationEffort:   5,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:unclosed-element",
			Name:                "Unclosed XML element",
			Language:            "XML",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"xml", "well-formedness", "syntax"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects an XML document that ends while one or more elements remain open.",
			Rationale:           "W3C XML well-formedness constraints require every opened element to be closed before the end of the document.\n\nSource: https://www.w3.org/TR/xml/#sec-logical-struct",
			Remediation:         "Add the missing end tag to close the element, or convert it to a self-closing element if it contains no child content.",
			CompliantExample:    "<root><item></item></root>",
			NoncompliantExample: "<root><item>",
			RemediationEffort:   5,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:multiple-root-elements",
			Name:                "Multiple XML root elements",
			Language:            "XML",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"xml", "well-formedness", "structure"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects more than one top-level document element in an XML document.",
			Rationale:           "The W3C XML document production rule requires exactly one root element per document. Multiple roots violate well-formedness.\n\nSource: https://www.w3.org/TR/xml/#sec-well-formed",
			Remediation:         "Wrap multiple top-level elements inside a single enclosing root element.",
			CompliantExample:    "<wrapper><first/><second/></wrapper>",
			NoncompliantExample: "<first/>\n<second/>",
			RemediationEffort:   5,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:undeclared-prefix",
			Name:                "Undeclared XML namespace prefix",
			Language:            "XML",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"xml", "namespaces", "syntax"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects an XML element or attribute using a namespace prefix that has not been declared.",
			Rationale:           "Namespaces in XML requires every prefix to be bound to a namespace URI via an xmlns:prefix declaration in the current or parent scope.\n\nSource: https://www.w3.org/TR/xml-names/",
			Remediation:         "Add an xmlns:prefix declaration for the namespace on the element or one of its ancestors.",
			CompliantExample:    "<root xmlns:cfg=\"http://example.com/cfg\">\n  <cfg:item/>\n</root>",
			NoncompliantExample: "<root>\n  <cfg:item/>\n</root>",
			RemediationEffort:   5,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:invalid-character-reference",
			Name:                "Invalid XML character reference",
			Language:            "XML",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"xml", "well-formedness", "syntax"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects malformed or out-of-range character references in XML text or attributes.",
			Rationale:           "W3C XML character reference rules require well-formed hexadecimal or decimal values that map to valid Unicode characters. Surrogates, nulls, and incomplete references are invalid.\n\nSource: https://www.w3.org/TR/xml/#NT-CharRef",
			Remediation:         "Correct the character reference syntax, ensure it terminates with a semicolon, and points to a valid Unicode character scalar value.",
			CompliantExample:    "<root>&#x20;</root>",
			NoncompliantExample: "<root>&#xZZ;</root>",
			RemediationEffort:   5,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:invalid-comment",
			Name:                "Invalid XML comment syntax",
			Language:            "XML",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityLow,
			Tags:                []string{"xml", "well-formedness", "syntax"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects comments that violate XML comment syntax constraints.",
			Rationale:           "W3C XML comment production forbids the string '--' within a comment body and requires that a comment does not end with '-'.\n\nSource: https://www.w3.org/TR/xml/#sec-comments",
			Remediation:         "Remove internal double-hyphens from the comment body and ensure it does not end with a hyphen before the closing delimiter.",
			CompliantExample:    "<!-- valid comment -->",
			NoncompliantExample: "<!-- invalid -- comment -->",
			RemediationEffort:   5,
			Detection:           rule.DetectionParse,
		},
	}
}
